### ISSUE TITLE
Support for polish characters

### ISSUE THREAD

**Issue by rika09** [bvschaik/julius#105]
Dunno if the c3 files are in polish but it is official translation.

**Comment by bvschaik** [comment]
I'm right now looking into the Russian translation, which contains extra files `c3_fonts.sg2` and `c3_fonts.555`. Are those two files also present on your Polish version?

And it would be useful if you could attach the c3_mm.eng and c3.eng (or the Polish equivalents of them) to this issue.

**Comment by rika09** [comment]
[Desktop.zip](https://github.com/bvschaik/julius/files/2878944/Desktop.zip)

![1](https://user-images.githubusercontent.com/38562081/52999143-5110ca80-3425-11e9-85c9-029293dbaccd.jpg)
![2](https://user-images.githubusercontent.com/38562081/52999167-5d952300-3425-11e9-9066-1070ce122e91.jpg)
![3](https://user-images.githubusercontent.com/38562081/52999176-638b0400-3425-11e9-8c22-6c75511fdf88.jpg)
![4](https://user-images.githubusercontent.com/38562081/52999182-68e84e80-3425-11e9-8c79-2330f0dbedef.jpg)
![5](https://user-images.githubusercontent.com/38562081/52999300-b1077100-3425-11e9-87f2-cc3351b97104.jpg)
![6](https://user-images.githubusercontent.com/38562081/52999305-b5cc2500-3425-11e9-990f-9bbc26a14e7f.jpg)

All files i have.

**Comment by bvschaik** [comment]
Thanks for the info. It looks like the Polish version has changed graphics to accommodate the extra Polish characters.

What are the problems you encounter when you use Julius with this Polish version?

**Comment by rika09** [comment]
![original](https://user-images.githubusercontent.com/38562081/53073611-cf827080-34e8-11e9-9209-abf7908ff1a9.jpg)

![vita](https://user-images.githubusercontent.com/38562081/53073621-d8734200-34e8-11e9-9e01-123398695e7e.jpg)

Second one is wrong on vita.

**Comment by bvschaik** [comment]
@rika09 I've briefly looked into this. Could you also supply the following files: `c3.exe`, `c3.sg2` and `c3.555`?

**Comment by rika09** [comment]
[Desktop.zip](https://github.com/bvschaik/julius/files/2973831/Desktop.zip)

**Comment by Piturzasty** [comment]
Also I tried to launch julius on Windows 10 and the same problem with strange font behaviour appears.

**Comment by bvschaik** [comment]
Yes, Julius was built for Windows codepage 1252 (= ISO-8859-1 / Western Europe) encoded version of the game, while the characters in the Polish version are most likely encoded using Windows codepage 1250 (more or less ISO-8859-2). This means that all accented alphabetic characters may be entirely different characters in Julius.

Since the encoding is implicit, that is: defined nowhere in the game or resource files themselves, I'll have to find a clever way to distinguish between the two.

**Comment by bvschaik** [comment]
By the way, the difficulty menu is called "pomoc" (help), so from the screenshot it looks like you didn't get the 1.1 update. Is that correct? Can you play custom scenarios?
We'll have to check if this is going to cause problems during gameplay.

**Comment by rika09** [comment]
Yes its without patch.

**Comment by bvschaik** [comment]
OK. We might need more changes than just the language support then. Could you also send `c3.emp` and `c32.emp`? Those were updated in the patch.

**Comment by rika09** [comment]
[Desktop.zip](https://github.com/bvschaik/julius/files/3016931/Desktop.zip)

**Comment by bvschaik** [comment]
Almost there! You can get the latest unstable build and try it out. Characters should display correctly for the Polish version, but there are some further changes necessary for the patch, because Julius is based on the patched version of C3.

For the patch, these new texts were added. Could you provide translations for the strings `formatted like this`? When I get them, I can prepare a Polish patch to official version 1.0.1.0.

In the File menu: `Delete game`
In the Options menu: `Difficulty`

Extra warnings:
- `Must be placed on edge of map`
- `Must place on open water`
- `Cannot place here`
- `No earthquakes are scheduled`
- `Some plots are too far from a road`
- `Parts of your city are boxed in`
- `People living there will soon perish`
- `Data limit reached - see readme`

Title for the "delete file" dialog: `Delete a file`

Religion advisor: `You have turned the effects of the gods OFF. Although they may be angry or pleased, they will not show it.`

Market lady information screen that shows what good she is fetching/returning: `Collecting:` and `Returning with:`

Difficulty settings dialog:
- `Difficulty settings`
- `Very easy`
- `Easy`
- `Normal`
- `Hard`
- `Very hard`
- `Gods effects OFF`
- `Gods effects ON`
- `Right click to exit`

**Comment by rika09** [comment]
Cant really translate this my english is good only on reading, exept for few lines it would be gibberish.

**Comment by bvschaik** [comment]
Alright. I'll have a go with Google Translate then. Could you check if the translation makes sense when I'm done? Or maybe @Piturzasty can help?

**Comment by bvschaik** [comment]
How do these sound?

In the File menu: `Delete game` -> `Usuń grę`
In the Options menu: `Difficulty` -> `Trudność`

Extra warnings:
- `Must be placed on edge of map` -> `Musi umieścić na krawędzi mapy`
- `Must place on open water` -> `Musi umieścić na otwartej wodzie`
- `Cannot place here` -> `Nie możesz tu umieścić`
- `No earthquakes are scheduled` -> `Nie zaplanowano żadnych trzęsień ziemi`
- `Some plots are too far from a road` -> `Niektóre działki są zbyt daleko od drogi`
- `Parts of your city are boxed in` -> `Części twojego miasta są nieosiągalne`
- `People living there will soon perish` -> `Ludzie tam mieszkający wkrótce zginą`
- `Data limit reached - see readme` -> `Osiągnięto limit danych - patrz readme`

Title for the "delete file" dialog: `Delete a file` -> `Usuń plik`

Religion advisor: `You have turned the effects of the gods OFF. Although they may be angry or pleased, they will not show it.` -> `Wyłączono efekty bogów. Chociaż mogą być źli lub zadowoleni, nie pokażą tego.`

Market lady information screen that shows what good she is fetching/returning: `Collecting:` -> `Zbiera:` and `Returning with:` -> `Wraca z:`

Difficulty settings dialog:
- `Difficulty settings` -> `Opcje trudności`
- `Very easy` -> `Bardzo łatwe`
- `Easy` -> `Łatwy`
- `Normal` -> `Normalna`
- `Hard` -> `Trudny`
- `Very hard` -> `Bardzo trudny`
- `Gods effects OFF` -> `Efekty bogów WYŁĄCZONE`
- `Gods effects ON` -> `Efekty bogów WŁĄCZONE`
- `Right click to exit` -> `Kliknij prawym, aby wyjść`

**Comment by rika09** [comment]
Must be placed on edge of map -> Musi być umieszczone na krawędzi mapy
Must place on open water -> Musisz umieścić na otwartej wodzie

Parts of your city are boxed in -> Części twojego miasta są nieosiągalne - "boxed in" this one i dont understand

Very easy -> Bardzo łatwy
Normal -> Normalny

Right click to exit -> Kliknij prawym przyciskiem myszy, aby wyjść - if there isnt any text limit

**Comment by crudelios** [comment]
"Boxed in" means they have no access to the road to rome, so no one can enter or leave that place.

**Comment by bvschaik** [comment]
Thanks for the corrections!

Like crudelios says: "boxed in" means there is no way to get in/out. Alternative phrases might be "cut off", "isolated", "locked in".

**Comment by rika09** [comment]
Parts of your city are boxed in -> Części twojego miasta są odcięte - i think its better but both sholud be good

**Comment by bvschaik** [comment]
Thanks!

Could you try the following:
1. Download the Polish patch files from: https://bintray.com/bvschaik/caesar3-patches/polish
2. Download the most recent unstable of Julius for your platform from: https://github.com/bvschaik/julius
3. Extract all files to your Caesar 3 folder, and run Julius

You should now be able to run the game in Polish, with all bugfixes and enhancements from the patch. Let me know if you encounter any issues.

**Comment by rika09** [comment]
Tried it and seems everything working thanks.

**Comment by bvschaik** [comment]
Great to hear, thanks for confirming!
