### ISSUE TITLE
Pop-up width

### ISSUE THREAD

**Issue by nwtour** [bvschaik/julius#138]
Pop-up window less than the original game. See screenshot:
Left - original game, right - Jullius
![screen](https://user-images.githubusercontent.com/3074285/55588170-c0bce980-5735-11e9-822e-438776deb563.png)

**Comment by bvschaik** [comment]
The sizes of the dialogs are based on the English text, which is much shorter. I'll have a look at them this weekend.

**Comment by bvschaik** [comment]
The dialogs from the help section are actually defined in the `.eng`/`.rus` files... And apparently the Russian version of the game ignores those completely... I'd love to increase the size of the help dialogs since they're made for 640x480 and we now have monitors way bigger than that, but it still needs to fit on 640x480. I'l have to think about how to solve this.

I'll be making other small changes to make text fit on the screen in other translations soon.

**Comment by bvschaik** [comment]
I have fixed all titles/texts that I could find. Could you have a look with the latest version?
