### ISSUE TITLE
Videos with german Files

### ISSUE THREAD

**Issue by Glurak18** [bvschaik/julius#161]
**Describe the bug**

I play Julius with the German version of Caesar 3 and everything works fine except when videos are playing. As example a fire is broken out. The Video works but the sound has a VERY TERRIBLE bug and it sounds like just wired noises. 

**To Reproduce**

1. Use German Files
2. Start the game
3. Just build houses.
4.  Wait until something burns.
5. Video Plays and you here the Ear Cancer. 

**Expected behavior**

Clear sound. 

**Saved games**

**Screenshots**

**Additional context**

**Comment by bvschaik** [comment]
Could you be more specific:
- Which operating system and version are you running?
- Which version of Julius?
- Can you upload the German fire video here?

**Comment by Glurak18** [comment]
1.Windows 10 64 Pro 
2. 1.1.0
3. Which file is are the Videos? I could but i think it wouldnt help you need the whole german version i think. Some Text is out of box too.  I could do a Iso out of my Disc. And send it to you.

**Comment by bvschaik** [comment]
The fire video is: `<Caesar 3 dir>\smk\city_Fire.smk`
But every video is broken, if I understand correctly?
(The intro video is not played in Julius, the intro screen you see is just an image plus a separate sound file.)

**Comment by Glurak18** [comment]
ah okay than add the Intro and yes is broken i did a video:
https://youtu.be/on_B3hbac_8 but lower your volume your you will be  deaf at the end.

**Comment by Glurak18** [comment]
[smk.zip](https://github.com/bvschaik/julius/files/3461364/smk.zip)

**Comment by bvschaik** [comment]
The videos are the same as the English ones, so they should play OK.
The Youtube video "has been removed by the user" - I'd love to be able to view it, because I cannot reproduce the issue on my end. Could you upload again?

**Comment by Glurak18** [comment]
https://youtu.be/Vb40V5GJZFM weired should work.

**Comment by Glurak18** [comment]
Maybe some other files in the german Version cause this error?  I mean there a many textboxes with text out of bounds too.

**Comment by bvschaik** [comment]
Thanks for the video; I hear two problems there: audio is garbled, and audio is played too fast.
I could reproduce the garbled audio, and fixed that in the latest unstable. Could you try 1.1.0.25-ea35f6f4 and see if that improves things?
Probably the audio is still played back too fast. In that case, could you attach `julius-log.txt` from your C3 folder?

Explanation: the "out of money" video (with German speech) is in 16-bit audio format, while the English videos are 8-bit, that's why the audio was garbled for that video.

Regarding the out-of-bounds texts: could you open a new issue for that and attach the German `.eng` files?

**Comment by Glurak18** [comment]
Ya new Unstable improves its now only very much to fast :-)

**Comment by bvschaik** [comment]
I think I found it. Could you try 1.1.0.27-5147902f?

**Comment by Glurak18** [comment]
Yepp worked :-) I tryed 1.1.0.28 :) 👍

**Comment by bvschaik** [comment]
Great to hear, thanks for the quick response!
