### ISSUE TITLE
Random crashes due to senate tooltip offscreen

### ISSUE THREAD

**Issue by danepowell** [bvschaik/julius#164]
**Describe the bug**
I've been playing Julius 1.1.0 for a few days and really love it, thank you!! I made it through the first few levels with no issues, but unfortunately I can't get through Syracusae because every ~30 minutes the game crashes to desktop. I'm not sure if this is specific to Syracusae, it could just be coincidence, but it's happened several times now and never on any previous levels. It's happened at various points in the level and after various delays, so I don't think it's tied to any specific in-game action or resource.

I'll attach the log, unfortunately the only thing of value there is a signal 11 error. Not sure if there's some way to enable debug logging?
[julius-log.txt](https://github.com/bvschaik/julius/files/3479112/julius-log.txt)
[Architectb1.zip](https://github.com/bvschaik/julius/files/3474732/Architectb1.zip)

**Comment by bvschaik** [comment]
It sounds like a memory corruption somewhere, but this will be very hard to debug...
The log you attached is from a normal exit, where did you see the signal 11 error?

Some questions first:
- Which operating system do you use?
- The crash didn't happen on previous levels, were those the regular campaign missions? (which basically can be completed within half an hour?)

**Comment by danepowell** [comment]
Apologies, I uploaded the wrong log. I've amended my original post with the correct log, which shows the signal 11 exit.

This is on Window 10. Yes, the previous levels were in the campaign so somewhat shorter than this one.

**Comment by bvschaik** [comment]
There's no extra debug logging available I'm afraid. I'll try to look into printing the stack trace this weekend, so we can hopefully debug this better.

Meanwile, could you try the [latest unstable (1.1.0.30)](https://bintray.com/bvschaik/julius/windows-unstable/1.1.0.30-f9e56269#files)? I upgraded the SDL libraries to 2.0.10 - maybe there were some crashfixes in the latest version.

**Comment by danepowell** [comment]
Same crash and error code in 1.1.0.30.

**Comment by bvschaik** [comment]
Ok, it took a bit of time but I have a build which prints at least a stacktrace. Could you try [julius-debug-1.1.0.31.zip](https://github.com/bvschaik/julius/files/3497935/julius-debug-1.1.0.31.zip)? If it crashes, please attach julius-log.txt again.

**Comment by danepowell** [comment]
[julius-log.txt](https://github.com/bvschaik/julius/files/3499129/julius-log.txt)

Crashed under similar conditions as before.

**Comment by bvschaik** [comment]
Thanks! I've been able to reproduce it: it's caused by drawing the senate tooltip when your senate is near the bottom of the screen.
Workaround for now is to disable tooltips (Help -> Mouse help should say OFF).

I'll have a look at it later today.

Full stacktrace:
ERROR: Oops, crashed with code -1073741819, generating stacktrace...
ERROR:   0x768889ea (null) memcpy (0)
ERROR:   graphics_save_to_buffer at C:/julius-mingw/src/graphics/graphics.c:181
ERROR:   save_window_under_tooltip_to_buffer at C:/julius-mingw/src/graphics/tooltip.c:91
ERROR:   draw_senate_tooltip at C:/julius-mingw/src/graphics/tooltip.c:217
ERROR:   draw_tooltip at C:/julius-mingw/src/graphics/tooltip.c:252
ERROR:   tooltip_handle at C:/julius-mingw/src/graphics/tooltip.c:273
ERROR:   window_draw at C:/julius-mingw/src/graphics/window.c:117
ERROR:   game_draw at C:/julius-mingw/src/game/game.c:146
ERROR:   run_and_draw at C:/julius-mingw/src/platform/julius.c:184
ERROR:   main_loop at C:/julius-mingw/src/platform/julius.c:327
ERROR:   SDL_main at C:/julius-mingw/src/platform/julius.c:503
ERROR:   main_getcmdline at /Users/valve/release/SDL/SDL2-2.0.10-source/foo-x86/../src/main/windows/SDL_windows_main.c:177
ERROR:   WinMain@16 at /Users/valve/release/SDL/SDL2-2.0.10-source/foo-x86/../src/main/windows/SDL_windows_main.c:205

**Comment by bvschaik** [comment]
Could you give 1.1.0.32 a try? The crash should be fixed now.

Exact steps to reproduce the crash in 1.1.0.31 and below:

1. Enable tooltips/"mouse help"
2. Build a senate
3. Scroll the map to put the senate at the bottom of the screen
4. Mouse over the senate to display the tooltip, such that the tooltip's bottom part is off-screen
5. Game crashes

**Comment by danepowell** [comment]
Awesome, thanks so much! I can confirm that the tooltip on the senate is the triggering factor here, and that 1.1.0.32 fixes it.

Thanks again for working through this with me.

**Comment by bvschaik** [comment]
Great, thanks for verifying and helping me debug this 😃
