### ISSUE TITLE
Unable to install on Mac 

### ISSUE THREAD

**Issue by jrinconhanna** [bvschaik/julius#166]
Hi, I'm using Porting Kit (based on Wine) to install caesar 3. As per instructions provided, I'm not sure how to get Julius started.

I'm not a developer and so it might be I'm not understanding the instructions well. Could anybody break the steps down for an absolute newb please? 

I'm really excited to play Julius. Thanks for the hard work.

**Comment by bvschaik** [comment]
Hi, sorry for not replying earlier, I've been away for the weekend.

You're right, I haven't put up Mac-specific instructions yet. If you have installed C3 using the porting kit, you should have a `Caesar 3.app` file somewhere. If that's the case, you can run Julius using the following steps. It's a bit of a hacky workaround but it will set you up until I have documentation written for this:

1. Download the latest version for Mac [here](https://bintray.com/bvschaik/julius/mac-unstable/_latestVersion#files)
2. Unzip the file and start julius.app
3. A popup will appear asking you to select the directory where the Caesar 3 files are.
4. Browse to the directory where you put `Caesar 3.app`
5. Here starts the hacky stuff because MacOS does not allow you to see into the .app file: press Cmd + Shift + G. Type `Caesar 3.app/drive_c` and hit Go
6. Then, browse farther to `GOG Games` -> `Caesar 3` and click `Choose`
7. The game should start.

Next time you don't need to do all the steps, just start Julius.app.
