### ISSUE TITLE
Windows 10 tiny cursor

### ISSUE THREAD

**Issue by dcnieho** [bvschaik/julius#173]
The in game cursor is tiny. This might well be because I'm on a dell laptop with 4K screen, display scaling in Windows is set to 250%. Is that honored taken into account by the game? I'd be happy to try and fix this one if you can't point me in the direction of where in the code the cursor is drawn.

This is on up to date Windows 10 Enterprise, running yesterday's nightly build.

**Comment by bvschaik** [comment]
That might indeed be related to the 4K screen and display scaling. Do the interface elements and city also look too small or are they OK?
Since I don't have a 4K screen (or Windows) this will be hard to debug... I'll check whether Julius supports display scaling on Windows; on my Mac it does, but that's a completely different implementation under the hood.

**Comment by dcnieho** [comment]
Whoops, i replied to these questions in the other item (#172) as well ;)

**Comment by dcnieho** [comment]
we may as well close this as discussion is taking place in #178
