### ISSUE TITLE
Pop-up window at launch

### ISSUE THREAD

**Issue by cyberdyne-sys** [bvschaik/julius#189]
When i launched the latest unstable version ( 1.1.0.168-83f26afd) i got a warning message, like this:

![image](https://user-images.githubusercontent.com/38621070/69977397-029f6900-152b-11ea-99ea-eaf95569308f.png)

As i know, it warns user, that patches for 1.0.1.0 aren't installed yet, but it never appeared earlier with my Caesar installation on Win 7. Is this a new feature, or a bug?

**Comment by bvschaik** [comment]
This is a new feature: there are missing strings in the language files, and some empire maps are completely unplayable with the unpatched version, so that's why I implemented the warning. Out of curiosity: which language are you using?

The message looks awful on Windows though. I'll see if I can improve that.

**Comment by cyberdyne-sys** [comment]
Yes, i see it now. This new feature works fine; i pasted the new patched files and the warning isn't appearing anymore. I use the english version of the game.
