### ISSUE TITLE
newer Simplified Chinese translation and other bugs for Chinese version

### ISSUE THREAD

**Issue by lingjiameng** [bvschaik/julius#192]
replace "後" with "后"， replace “於” with "于"
[Simplified Chinese translation.txt](https://github.com/bvschaik/julius/files/3936497/chs.txt)

**Comment by 411752230** [comment]
Inconsist texts between the original and the julius's
original (correct:战争与和平)
![4G3 N12Q$1}}O)`CX83Y(E2](https://user-images.githubusercontent.com/14128007/70392051-861ef580-1a16-11ea-93d4-0925f8e1f349.png)
julius's (messy and meaningless:战援监)
![](https://files.gitter.im/julius-game/community/k5Q2/K72-ILCBRR-BVO4BJT0Y-U.png)

Problem to be resolved.

**Comment by 411752230** [comment]
Replace 
"後" with "后" 
“於” with "于"
“紮” with "扎"
“夥” with "伙"
“徵” with "征"
“「」” with " “” "
redundant “一” with “—”

Last update date:12/09/2019
[chs.txt](https://github.com/bvschaik/julius/files/3936628/chs.txt)

This should be the last for the Simplified Chinese font. Further modification needed if something unexpected happened during the future test.

**Comment by bvschaik** [comment]
For the links in the help section: please verify that this build fixes it: https://bintray.com/bvschaik/julius-branches/windows/chinese-1.1.0.185-3fd7cc01#files
In this build, I also reverted the font back to "bold". Tomorrow I'll implement the semi-bold one we discussed in the chat.

**Comment by lingjiameng** [comment]
> Replace
> "後" with "后"
> “於” with "于"
> “紮” with "扎"
> “夥” with "伙"
> “徵” with "征"
> “「」” with " “” "
> redundant “一” with “—”
> 
> Last update date:12/09/2019
> [chs.txt](https://github.com/bvschaik/julius/files/3936628/chs.txt)
> 
> This should be the last for the Simplified Chinese font. Further modification needed if something unexpected happened during the future test.

I think「」looks better，it's unnecessary to replace it with ""

**Comment by 411752230** [comment]
「」is commandly used in traditional Chinese while “” is more popular among Simplified Chinese nowadays as i find there is no “” in the font support.

**Comment by 411752230** [comment]
You can see a opensource app convertZZ from github.All the「」is to be rendered to “”. 「」is widely used in traditional Chinese and Japanese. Although「」may looks better, in my op, “” is much more commonly used than the previous for Simplified Chinese. As the txt did not has “” at all, we may found font missing when translating new texts like assignment editor unless we adopt the old-styled「」wholeheartedly.

**Comment by 411752230** [comment]
Sorry me again. I feel bad.
Extra char.
![QQ截图20191209103421](https://user-images.githubusercontent.com/14128007/70402779-813a6000-1a6f-11ea-9906-802937be3bb1.jpg)
Replace 接 with 按
redundant 具 with 瓦

Found a new problem concerning punctuation "·"

original traditional Chinese （√）
![C40Y))4)2DFZK`_ PBG{O%L](https://user-images.githubusercontent.com/14128007/70403784-e5125800-1a72-11ea-8476-51030d5a935e.png)

new simplified chinese rome.555 （×）
![X0{B_UU}922Y2 1 O9)H2GI](https://user-images.githubusercontent.com/14128007/70403937-505c2a00-1a73-11ea-8319-7639c2216bb7.png)

the backup picture [https://user-images.githubusercontent.com/14128007/70248665-3215d600-17b6-11ea-84e1-7cd0412d38b8.png](url)
![QZ494EWN`R$@D}_)Y6P$28](https://user-images.githubusercontent.com/14128007/70403989-85687c80-1a73-11ea-805c-49a9234bbe10.png)

**Comment by 411752230** [comment]
@bvschaik Another bug with the latest julius you provided both in Eng and Chinese version. Start a new game and give yourself a new name. set some housing and waiting for the fire broken. You will see no matter what name you have set the governer's name is always "the new governer"

**Comment by bvschaik** [comment]
> @bvschaik Another bug with the latest julius you provided both in Eng and Chinese version. Start a new game and give yourself a new name. set some housing and waiting for the fire broken. You will see no matter what name you have set the governer's name is always "the new governer"

Good one. I created a new issue for that.

**Comment by 411752230** [comment]
@bvschaik Could you give an update to the rome.555 of Simplified Chinese?

I have been playing julius with the new rome.555  you created for long. Until now, the amendment of the txt was last updated on 12/18/2019 since I didnt find anything new to improve further. I'd like to finish the txt first, so we can head into other questions concerning it soon.

**Comment by bvschaik** [comment]
@411752230 I haven't had time to look further into it (and I was waiting for you to complete the txt file). I'm preparing a 1.2.0 release at the moment, but after that I should have some time to work on the Simplified Chinese version again.

**Comment by 411752230** [comment]
> @411752230 I haven't had time to look further into it (and I was waiting for you to complete the txt file). I'm preparing a 1.2.0 release at the moment, but after that I should have some time to work on the Simplified Chinese version again.

Thanks. I will give my last spot on the txt before julius 1.2.0. 

Additionally, how is it going with the engconverter? Maybe I could answer the question you mentioned that what I will modify in the traditional Chinese eng for now. In fact, there is a big difference between TC and SC.

During the period when I watched the game carefully with it texts, there are many expressions of the localization of TC not authentic but not unacceptable as the demands of idiomatic SC expressions. Sometimes they are old-styled and obscure in wording by using uncommon characters and phrases in comparision with the wording of SC nowadays. 

Even more there is a mistaken character inputted I found in the brief description of the map Corinthus. It's 贸易 （Mao Yi, means trade） rather than 冒易, and an extra space in that of the map Hierosolyma. By the way, would it be possible for the engconverter not only can edit eng but also translate brief description of a map？

![QQ截图20200107123137](https://user-images.githubusercontent.com/14128007/71868611-d68a8f80-3149-11ea-88cb-84677da1fd05.jpg)

We can only input ABC here in the assignment editor but no way for chinese characters you know. I just cannot make it out how could the translators back in the days get the brief descriptions translated. I dont suppose it would be a good news if we can translate the map description.

**Comment by 411752230** [comment]
Some notes concerning mistranslation of original Chinese:

1.Chinese original mistranslated index of "iron"(铁矿) in the description of Weapons Workshop(武器厂) misleads to the "Olive and Vine Farm"(橄榄园及葡萄园).
![QQ截图20200109213534](https://user-images.githubusercontent.com/14128007/72072527-25dae680-3329-11ea-900a-9d138aef0263.jpg)
![QQ截图20200109213630](https://user-images.githubusercontent.com/14128007/72072491-0fcd2600-3329-11ea-9cc6-7713175aceed.jpg)

Proposal: Edit the C3_mm.eng when engconverter supporting Chinese in the future.

2. Translation mistakes
"哪里" rather than "那里"
![QQ截图20200109213431](https://user-images.githubusercontent.com/14128007/72072822-b1ed0e00-3329-11ea-8400-3cf5c7046ebd.jpg)
"贸易" rather than "冒易"
![QQ截图20200109213658](https://user-images.githubusercontent.com/14128007/72072913-d648ea80-3329-11ea-8233-ecf2f72b7a6b.jpg)

Obstacles: 
1.No char "哪" at all in the original TC rome.555 and the total of 2188 chars cannot be exceeded.
2. No way for edit Chinese into map description for now.

**Comment by 411752230** [comment]
Missing translations
![QQ截图20200117181724](https://user-images.githubusercontent.com/14128007/72604688-630d2d00-3956-11ea-9667-f20152908154.jpg)
![QQ截图20200117181955](https://user-images.githubusercontent.com/14128007/72604696-66081d80-3956-11ea-9358-08342ffff9c2.jpg)

**Comment by 411752230** [comment]
> And for Chinese we have the added complexity that the settings cannot use any other characters than the 2188 that are defined in the graphics file.

@bvschaik Understood, good news is that in the chinese graphics there are some duplicate even triplicate chars after simplification (The original TC graphics has used some chars with their traditional and simplified forms all existed. I have made notes for those). 

And up to now the number of the new chars needed to be added is less than that of the repetitive. As for the new configuration options, I believe the existed chars are far more enough to translate it. 

The only thing I need is that I am able to input and identify the mapping code of the 2188 chars.

**Comment by bvschaik** [comment]
Since we now have support for the "official" Simplified Chinese translation, I'm closing this issue.

**Comment by 411752230** [comment]
Notes of the "official" Simplified Chinese translation

1.档案 rather 档盎
![QQ截图20200717081332](https://user-images.githubusercontent.com/14128007/87734563-8cbfe780-c805-11ea-9086-e659d41ddf5d.jpg)

**Comment by bvschaik** [comment]
I've created a new issue (#507) for problems with the SC translation: since this issue is closed I don't see the replies in the issue list.
