### ISSUE TITLE
Amphitheater glitch on Tarraco

### ISSUE THREAD

**Issue by falconepl** [bvschaik/julius#198]
**Describe the bug**
A building glitch shows up on the Tarraco map whenever the save is loaded. Sometimes it appears instantly after the save is loaded, sometimes it takes a few seconds to show up

**To Reproduce**
1. Load the save file provided

**Expected behavior**
We should not see the boxed amphitheater near the earthquake cracks. There's no building there

**Saved games**
[Julius-V-01.zip](https://github.com/bvschaik/julius/files/3969878/Julius-V-01.zip)

**Screenshots**
<img width="522" alt="tarraco" src="https://user-images.githubusercontent.com/1430549/70938503-90f50e00-2046-11ea-950b-3e3cb7cc865a.png">

**Additional context**
The red blocks on earthquake cracks don't show up every time (not for every save file that contains the amphitheater glitch). But the glitch for the amphitheater appears every single time and stays in its place even when restarting the game

**Comment by crudelios** [comment]
I think I found the reason for both glitches.

**Steps to reproduce:**
* Load a new `Tarraco` scenario
* Place buildings on spots where the earthquake will destroy them
* Let the quake destroy the buildings
* Create many new buildings anywhere you wish
* Select the `clear land` button and hover your mouse over the `cracks in the land` tiles. The new buildings will also be highlighted in red

I'm thinking this bug happens because the `cracks in the land` never really remove the building ID from the tile, even though the ID is freed for a new building. So when a new building is created with the same ID, julius considers the building to also be located on the earthquake tile where the original building with that ID was.

Also, upon further testing, I found this bug also happens on the original C3. The following is a `sav` file created exclusively with C3, and you can see that the red highlight bug exists.

[earthquake2.zip](https://github.com/bvschaik/julius/files/3970314/earthquake2.zip)

The bug has two main effects
* Because the `visual feedback on delete` relies on building ID's, it's very easy to spot which `crack` tile has the same ID as a new building
* If the new building with the same ID has an animation (such as a theater, reservoir, amphitheater as seen in the image, and even a colosseum - I tested), the animation will not only draw on the bulding, but in the `crack` tile with the same ID.

So, my question is: since this is a bug from the original game, should we fix it?

**Comment by bvschaik** [comment]
I think we should fix this. I'll work on it this evening: the fix itself is trivial (thanks @crudelios for debugging this!), but the tests should be updated as well.
