### ISSUE TITLE
License conflict with libsmacker

### ISSUE THREAD

**Issue by CrossVR** [bvschaik/julius#200]
It seems libsmacker is licensed under a non-commercial license, this conflicts with the commercial-use rights given under the AGPL license that Julius uses.

> libsmacker is released under a Creative Commons Attribution Non-Commercial License V2.0. This means, first, that projects using libsmacker must indicate somewhere that they use libsmacker in the code. Also: the Non-Commercial tag means exactly what it suggests: LIBSMACKER MAY NOT BE USED IN ANY COMMERCIAL PROJECT. PERIOD. Non-commercial DOES NOT mean simply "non-profit": commercial includes for-profit, but may also encompass other non-profit activites as well.

Effectively this means that either libsmacker needs to be replaced or the AGPL license that Julius uses needs a non-commercial use clause added to it (with the appropriate permission from contributors).

**Comment by crudelios** [comment]
I don't see why Julius is incompatible with libsmacker. Julius itself is not a commercial project. Even though julius can be used in commercial projects (due to AGPL v3.0), it doesn't mean every one of its libraries can.

Even though the source code for libsmacker is included in Github, at no point is it meant or implied that the libsmacker library is under the AGPL license.

What this means is that any commercial project using Julius must either develop their own smacker library, or request permission from the libsmacker creator to use it. At that point, it is up to the libsmacker creator to enforce his rights.

What *could* be done is to better inform that the compiled files use libsmacker and, if any commercial project wishes to compile or use their own copy of Julius, they must request permission from the creator of libsmacker.

Either way, I explicitly agree to any change in the license terms for Julius.

**Comment by Armada651** [comment]
> Even though the source code for libsmacker is included in the Julius repository, at no point is it meant or implied that the libsmacker library is under the AGPL license.

When you distribute a build of Julius then AGPL applies to the whole thing, including the libsmacker parts that are under a different license that is not compatible with the GPL.

**Comment by crudelios** [comment]
> When you distribute a build of Julius then AGPL applies to the whole thing, including the libsmacker parts that are under a different license that is not compatible with the GPL.

Humm I see what you mean. The source code itself doesnt' violate libsmacker's, but the compiled code contains licenses that both allow and disallow commercial use.

This becomes a problem because we distribute compiled executables.

**Comment by Armada651** [comment]
Exactly, at the very least the ReadMe should indicate that a build of Julies with Smacker support is for non-commercial use only.

However without an exception in the license anyone who does build Julius with smacker support is technically violating the license. This is why projects add those linking exceptions to their license.

**Comment by crudelios** [comment]
Also, Julius can easily be made to work without using libsmacker as the videos are optional. Adding a `WITHOUT_LIBSMACKER` define would be easy enough and would mitigate any eventual violation.

**Comment by Armada651** [comment]
Then that's what should probably be noted in the ReadMe, that in build configurations that have libsmacker support you lose your right for commercial use.

Builds with smacker support would still violate the license, but at least that way nobody is caught by surprise.

**Comment by crudelios** [comment]
As a heads-up, we are actively trying to solve this problem.

**Comment by Armada651** [comment]
That's great, to clarify I don't have a commercial use for it. I just wanted to point out the conflict because it affects your free software status.

**Comment by greg-kennedy** [comment]
FYI as a result of this issue, I have changed the license of libsmacker to LGPL v2.1.  I understand you all have your own implementation now (courtesy @bvschaik) but for others who still wish to use the library in their projects, take note :)

**Comment by Armada651** [comment]
That is an excellent result, I'm sure open-source retro remakes will appreciate the new license.

> I personally saw no issues with Julius using libsmacker of course, as it was clearly not a commercial endeavour, but I am not a lawyer

The problem was that as far as the license is concerned somebody could take Julius and use it in a commercial endeavour. At which point it would become an issue even though the license on the code was followed correctly.

**Comment by AJenbo** [comment]
> FYI as a result of this issue, I have changed the license of libsmacker to LGPL v2.1. I understand you all have your own implementation now (courtesy @bvschaik) but for others who still wish to use the library in their projects, take note :)
> 
> (I personally saw no issues with Julius using libsmacker of course, as it was clearly not a commercial endeavour, but I am not a lawyer)

Thanks for this, now we won't have to migrate away from it in https://github.com/diasurgical/devilutionX :)
