### ISSUE TITLE
Do Pharao&Zeus use a similiar engine?

### ISSUE THREAD

**Issue by yoshimo** [bvschaik/julius#222]
Since they are all done by Impression Games and Activision, are the cames from caesar1 to Zeus similar enough to have one open source re-implementation run these games together?

**Comment by bvschaik** [comment]
Sadly, no. Caesar 1 and Caesar 2 are DOS games, so they're totally different. Pharaoh, Zeus and Emperor are next iterations of the same "engine", but quite different.

**Comment by yoshimo** [comment]
DOS is of course different. :)
Would you be intrested to go for the sequels once caesar is doing well?

**Comment by bvschaik** [comment]
Getting this far for Caesar 3 took me 11 years. Even though I would like to have open source implementations of the sequels, my life is different now and I simply don't have the time to make them.

**Comment by crudelios** [comment]
If we had the resources we could even create an all-in-one customizable engine with on/off support for each of the game's features. Imagine being able to build pyramids in Caesar 3 just by changing a setting!

Unfortunately that takes a lot of resources and personal investment. This project has largely been @bvschaik's sole endeavour, with some contributions along the way.

So, is it possible? Get ten eager programmers, two years, some organization between them and a lot of dedication and maybe yes. Otherwise, no.

**Comment by devnoname120** [comment]
https://github.com/bvschaik/julius/issues/108

**Comment by dalerank** [comment]
@crudelios  @yoshimo  FYI:  some times ago I created clone of C3 (here https://bitbucket.org/dalerank/caesaria ), it can use resources from original c3/pharaoh/zeus game, using modern engine with scripts, but... I stop develop after received IP violation from activion and ban my accounts on github/steam/ and some resources

**Comment by Jaroslav80** [comment]
Dalerank - long live to companies which published games in modding friendly manner and pushed fans into modding instead of forbidding it. Developers which after first (commercially) most important years described files in their engine or provided source code at least to major fans websites. 

Knights of Honor, Europe Universalis, Cossacks, Sin's of Solar Empire, Revenge of the Titans, ... 

Sierra, Impressions Games, Blizzard - doesn't seem to be the case. But for 20 years they were not able to create accessible and playable remake of their good old games.

**Comment by yoshimo** [comment]
@dalerank what did they base their takedown on? If people own the original files to play , no monetary harm is done. If you replace the assets and use an own engine, what harm is done either?
Many games look similiar and have a similiar setting compared to other games.

**Comment by dalerank** [comment]
@yoshimo IP violation for settings, gameplay and game logic :)

**Comment by yoshimo** [comment]
they need to threaten a few more developers this year: https://www.youtube.com/watch?v=mlZvQXJ8g_s lists a lot of egypt city builders, some even very close to the look and feel.
