### ISSUE TITLE
New main menu

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#224]
Could this be done?

![image](https://user-images.githubusercontent.com/47231209/72224285-80f22080-3557-11ea-8414-d8cbdcdcad5a.png)

Ignore the widescreen background with the Caesar III logo, i know that cannot be done right now.

- Continue -> Resumes the last saved game
- New Game -> Campaign or Skirmish
- Load Game -> Savegames list
- Options -> General game options from sound to game resolution
- Credits -> Credits .SMK
- Map Editor -> Self-Explanatory
- Cutscenes -> Opens up cutscenes tab for you to pick which you wanna play

**Comment by bvschaik** [comment]
No. We cannot use strings that are not in the original game.

**Comment by 411752230** [comment]
@bvschaik Is the "C3 AE needed" message from the original texts of the game?

**Comment by bvschaik** [comment]
No. These and the "you do not have the patch" messages are always in English. But for regular in-game texts I do not want to use non-existing strings, since that requires the user to download new language files, and me to provide them in all languages. I'm not fluent in 8 languages, nor do I want to maintain language files.
