### ISSUE TITLE
That annoying gatehouse road!

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#233]
All of you know that...

![step1](https://user-images.githubusercontent.com/46932541/72427901-60afa500-3795-11ea-980d-f2dfbf263a6d.png)
Build some gatehouse
_______________________

![step2](https://user-images.githubusercontent.com/46932541/72427964-745b0b80-3795-11ea-88f8-07b4f8bcb727.png)
Then delete that useless part of road
_______________________

![step3](https://user-images.githubusercontent.com/46932541/72427967-745b0b80-3795-11ea-899f-f41e97d46a65.png)
Seems to be ok... 
_______________________

![step4](https://user-images.githubusercontent.com/46932541/72427968-74f3a200-3795-11ea-8005-3010eef3e8a7.png)
Now we need to rotate camera
_______________________

![step5](https://user-images.githubusercontent.com/46932541/72427969-74f3a200-3795-11ea-994b-1aa93062e161.png)
WUT? That piece of sh..road came back! Only way we can handle it is...
_______________________

![step6](https://user-images.githubusercontent.com/46932541/72427970-758c3880-3795-11ea-8e9e-c345a0ff6275.png)
... to keep that tile busy by some buildings
_______________________

Maybe, it makes sense to fix that oldie one? Thanks!

**Comment by 411752230** [comment]
LOL

**Comment by crudelios** [comment]
Best bug description ever!!! 🤣

A very very old julius branch of mine that fixes the issue: https://github.com/crudelios/julius/tree/prevent-gatehouse-roads-on-map-rotate

But it probably won't be fixed in Julius for now as the idea is to keep the behavior of the original C3, including the annoying things. So stuff like UI improvements can be changed, but now gameplay bugs.

Anyway, it's up to @bvschaik to decide!

**Comment by bvschaik** [comment]
Agreed, I hereby award @ArtySh0ck the Julius prize for most amusing bug description 😂 

I didn't even know this "feature" existed, since I do not rotate the map often during play. I know we duplicate the behaviour of C3, but in this case I think that fixing it makes more sense. Rotating the map should not magically cause roads to spawn.

**Comment by crudelios** [comment]
> but in this case I think that fixing it makes more sense.

Well, well! I always thought you'd say no! I'll PR my branch then 😛

**Comment by ArtySh0ck** [comment]
Thank you all! I love you! =) will waitin for next version )

**Comment by KillahNeo** [comment]
Why not fix the bugs.. Just to keep old savegames compatible? Not worth it..
