### ISSUE TITLE
Ballista versus clear land

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#240]
Clicking clear land makes ballista disappear and getting out of clear land makes the ballista reappear
![](https://files.gitter.im/julius-game/community/XpO6/QQ-Jie-Tu20200117221050.jpg)

![](https://files.gitter.im/julius-game/community/Bkca/QQ-Jie-Tu20200117221226.jpg)

**Comment by crudelios** [comment]
Bug related to #120.

**Comment by devnoname120** [comment]
Can you confirm that it doesn't happen in the original game?

**Comment by 411752230** [comment]
> Can you confirm that it doesn't happen in the original game?

Confirmed. It doesn't happen in the original game

**Comment by bvschaik** [comment]
I think I found the problem but I'm not at my computer so I can't check.
https://github.com/bvschaik/julius/blob/a72272eff3f1de7d93e5ca7e28d85b8c3816128b/src/widget/city_without_overlay.c#L440-L453
Here we draw everything in one pass, instead of multiple passes like in the non-deletion code. This causes the tower to be drawn on top of the ballista.
@crudelios Could you perhaps take a look?

**Comment by crudelios** [comment]
Sure, I'm thinking about implementing visual feedback for overlays anyway,I'll do it in one go.

**Comment by bvschaik** [comment]
Hippodrome still has issues with the horses walking in front of the pillars and fire columns.

<img width="188" alt="delete-hippo" src="https://user-images.githubusercontent.com/104874/72661812-2b969300-39df-11ea-95fa-8c5ef8c37312.png">

**Comment by crudelios** [comment]
I didn't notice that! Easy fix though, you've done it already.
