### ISSUE TITLE
Sound options and AE intro video

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#249]
![](https://files.gitter.im/julius-game/community/61FP/QQ-Jie-Tu20200119003448.jpg)
Clicking 'Cancel' here will replay the background music

![](https://files.gitter.im/julius-game/community/PQCQ/QQ-Jie-Tu20200119004930.jpg)
Will map_intro.smk be added later?

**Comment by KillahNeo** [comment]
I wish it was, as it is on the original.

**Comment by bvschaik** [comment]
**Please report just ONE issue per ticket: that way it's easier for me to keep track of things.**

Music will be fixed with @jfconecn's PR.
Regarding the intro video for the map editor: I think it does not add anything, so no, that will not be added.

**Comment by 411752230** [comment]
> **Please report just ONE issue per ticket: that way it's easier for me to keep track of things.**

> Regarding the intro video for the map editor: I think it does not add anything, so no, that will not be added.

Come on. I have thought that there are too many issues for you to settle.

Why not? Its an original asset of C3. I dont think it's good idea to cut it. It at least could play a role in the prologue of AE. By the way, if things go in the way you described, the intro videos button is useless too which also didnt add anything but some outdated graphics.

**Comment by bvschaik** [comment]
> Come on. I have thought that there are too many issues for you to settle.

Many issues are not a problem. The problem with multiple issues per ticket is that I cannot keep track. For example: once the sound issue is fixed I cannot close this ticket because we're still discussing about the editor, so I have to keep track of sub-issue status in my head or read the whole comment thread again, losing time in the process which is better spent on other things.

> Why not? Its an original asset of C3. I dont think it's good idea to cut it. It at least could play a role in the prologue of AE. By the way, if things go in the way you described, the intro videos button is useless too which also didnt add anything but some outdated graphics.

It's an original asset, but in my opinion a useless one, and where would we want to play it? When you click the editor button on the main menu? That's just annoying. And what value does the editor intro movie add? Nothing. The intro videos supply some historical information, and that's the only reason those are back.

**Comment by 411752230** [comment]
Understood.😬 alright then close this issue with sound bug resolved.
