### ISSUE TITLE
Project Objectives

### ISSUE THREAD

**Issue by polaretto** [bvschaik/julius#25]
Hi, 

I'm seeing that most of the recent commits have the purpose of (correctly) separating the all-together code in more specific areas, like UI, game logic etc.. 
I was wondering, what is the objective at the end of that? What are, in your opinion, @bvschaik the things this project needs and the ultimate goal you are willing to achieve? How far are we from that?

**Comment by dalerank** [comment]
Final goal, imho, restore workable implemetation of original :)

**Comment by polaretto** [comment]
Ok good, but how far are we from that? It appears to me that in terms of functionalities we are almost there (tried to play a mission I previously played in the original game and got almost the same playing experience). 
Maybe to do bigger steps we should have a bigger community, which I think cannot be developed without proper documentation of the project and of the code.
Furthermore the code may be "workable" but it is far from "clean"... It is a big bunch of if/else and switch/case branches, which not only it doesn't really abstract the behavior, but it doesn't have a single line of comment explaining why things are done in a specific way.

**Comment by dalerank** [comment]
Repoowner workout for this project over 7 years, as I mind correct. @bvschaik

**Comment by polaretto** [comment]
And that's indeed an incredible work, I did not want, in any way, say that's bad (sorry, English is not my primary language). What I just wanted to make clear is that maybe with some clarification of the objectives, we can also give better help, that's all :)

**Comment by dalerank** [comment]
Seems to be need goto to other lang c++(imho) or script with c++, but in plainc it really hard to update.

**Comment by bvschaik** [comment]
A bit of history for this project: it started in 2008 when I learned to read assembly and slowly discovered how the game worked. Around 2011 I started on a remake of Caesar 3, and after a few false starts I created this repository. At first I focused on recreating the original functions and grouping them in files, the past half year or so I've been separating UI and logic, separating the records in the .sav files from their representation in memory, abstracting away global variables, and (hopefully) improving the code.

It's in C because the original was in C. It has many switch and if/else statements because that's what the original has. I agree that it's not the most beautiful codebase you will ever see, but considering where it came from, it's way better already. Do I want to migrate to C++? Maybe, but Julius has been eating up too much time already and I'm not too familiar with C++.

The original goal was, as @dalerank mentions, to have a working copy of Caesar 3, an exact copy gameplay-wise, but with UI improvements such as widescreen support and support for multiple operating systems. Apart from any bugs that I undoubtedly have introduced, this goal is almost reached, after I migrate the last bits of 'old' code.

Then, things that still have to be done on the short term:

- Find a way to build/distribute the game and make it easy for users to get up and running. For Windows, this simply involves dropping julius.exe and the SDL dll's into the game folder. For Linux and macOS, it's a whole different story because those users need to get the assets from the original game.
- Write documentation: readme, compile instructions, installation instructions, you name it.
- Try to hunt down the bugs.

For the long term, I don't have any concrete plans, but integrating the scenario editor might be a nice one.

**Comment by polaretto** [comment]
The work you have done, alone, is really impressive and that's why I wanted to learn more about it in the first place. 

1. Distribute: Can help about Windows and Linux, no idea about macOS honestly. Maybe we could plan a "Release"?
2. Documentation: I'll definitely help with that while diving in more into the project. Maybe setting up a wiki could be useful to put all the information together (maybe within github?). For example I may try to write some docs explaining the hierarchy of the program and you could integrate/correct thanks to your experience, what do you think?
3. Bugs: Clearly will help about that 😄 
4. Editor: Quite interesting indeed.

**Comment by devnoname120** [comment]
I would like to fix a few bugs as well, just like OpenRCT2 does.

Also, I believe that a few additions could be made. @bvschaik, would you agree that for instance I add roadblocks to the game once the refactoring is finished? They were added in all the next Sierra games, and I think that not having them (and using gatehouses as an ersatz) is a significant gameplay hurdle.

**Comment by bvschaik** [comment]
Which bugs do you think that should be fixed? Besides the 100-year-old ghosts there aren't any major gameplay bugs that I can remember.

I want to keep Julius close to the original gameplay wise, and the .sav files fully compatible with Caesar 3. That means that introducing roadblocks is out of the question. Maybe we should create an enhanced edition of Julius?

**Comment by jurf** [comment]
Hey, I’d like to jump aboard and help the tiny amount I can manage. I’ll create a PR with my [Flatpak](https://flatpak.org) manifest once it’s done.

> Seems to be need goto to other lang c++(imho) or script with c++, but in plainc it really hard to update.

May I suggest [Rust](https://rust-lang.org) instead? It has many benefits and wouldn’t require a complete rewrite, since the C and Rust parts can coexist as if they were on language.

BTW @dalerank what’s the relationship between this and Caesaria (and you)? Is Caesaria dead, or obsoleted by this?

**Comment by Quix0r** [comment]
To write down what I think: Keep the spirit of the original game in while providing modern OpenGL features under the hood, like other famous clones do. Maybe one day, start with an enhanced edition, still allowing to "import" C3 save games (but no export to C3, of course) but having more improvements/additions.

Only a few thoughts (long-term goals?):
1) Missing features that people ask to be added (and makes sense, no space port is making sense here)
2) HD textures (only **optional**, spirit is maybe lost when you use them).
3) Refacturing the engine (get rid of re-implemented bugs, making it more modular/plug-able) like the clone of WarZone2010 does
4) Addon system to allow people adding/replacing content (again WZ2010 does this)
