### ISSUE TITLE
Stop repeating images

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#252]
Simple improvement over what we have right now, instead of repeating the same UI image on top of each other a thousand times why not just stop at the first repetition and leave the rest as open space?

![image](https://user-images.githubusercontent.com/47231209/72688931-dba4f280-3aea-11ea-873a-d76e4ca10a4d.png)

**Comment by crudelios** [comment]
This one is not so simple as it looks, those images are there because the city is only drawn horizontally until the image. Drawing the city for the whole screen and then "covering" with the menus is also not simply doable, due to the way code is implemented.

To be clear: I don't mean to say it's impossible, just very time-consuming.

**Comment by bvschaik** [comment]
> To be clear: I don't mean to say it's impossible, just very time-consuming.

Exactly. Not to mention that performance will suffer on higher resolutions because of it.
