### ISSUE TITLE
Visualize walker behavior

### ISSUE THREAD

**Issue by HoratioVex** [bvschaik/julius#259]
One of the great shortcomings of the whole Impressions series is intransparent walker behavior. The player is asked to predict how they will behave, but since the game offers insufficient information, forms all kinds of false theories around them and gets frustrated when they fail. The game should be better at teaching players how this key mechanic works internally.

When clicked for info, a walker should:
* If on a targetted walk, highlight its target. I think this could be a building, a road tile or a map tile before its mapped to the closest road. (But if I fully understood the process, I wouldn't have to file this request 😃)
* If patrolling randomly, display a circle of highlighted tiles around itself, whose radius shows the number of steps remaining.
* If returning, highlight its home in a different color.

**Comment by crudelios** [comment]
This seems like an extremely complex feature to implement. I'm not even sure it's possible to detect beforehand all the routes a walker may take.

An implementation idea would be to create a new `Figure` overlay. By default it would display all the walkers and no buildings. Clicking on a specific walker would show the routes as described by @HoratioVex, and if it was a destination walker it would display the destination building, if applicable.

Possible paths:
* green tint in path and displaying building: destination walker, path to building; 
* green tint and no building displaying: random walker, possible paths;
* red tint and displaying building: random walker returning, path to base.

@bvschaik, besides the required processing power to constantly calculate the path (which, I figure, would be a lot), is this technically possible? The `Figure` string exists in the language file, so that's not  a problem.

Also, this would be a long-term project, if we ever start it.

**Comment by HoratioVex** [comment]
While predicted _paths_ sure sound nifty, I should note that my suggestion only describes showing either a target tile or an approximate radius. I assumed that both would have to be already calculated and stored when the walk begins.

**Comment by bvschaik** [comment]
Nice suggestions but too much of a UI change to incorporate into Julius.
