### ISSUE TITLE
windows installation readme update

### ISSUE THREAD

**Issue by charlieysc** [bvschaik/julius#270]
Tried the installation for windows until MinGW-w64 step and found out that step 1 download link points to the incorrect installation file. The current link points to the source file for MinGW-w64.

It should be this link
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe

Found it on their page, https://sourceforge.net/projects/mingw-w64/files/mingw-w64/ at the section "MinGW-W64 Online Installer"

**Comment by crudelios** [comment]
Hi,

Yes, the instructions are outdated. I even submitted a change for the link, but then went back because the base instructions are already very outdated (they still work except for the link, but there's an easier way to build Julius now).

Anyway, I'm waiting for the Android build to be merged so I update all the instructions.

**Comment by bvschaik** [comment]
For now I'll update the link and close this issue.
