### ISSUE TITLE
Original bug: Unsaved city flag of new-opened trade route

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#276]
Six assignment: Lugdunum

A new southern city "Massilia" will be available to trade with later, whose flag should become red.
![QQ截图20200126002046](https://user-images.githubusercontent.com/14128007/73124125-955fff80-3fd2-11ea-962c-411d4ff6f533.jpg)

But after you save the game and load it, the city flag turns to blue again.
![QQ截图20200126002126](https://user-images.githubusercontent.com/14128007/73124131-aa3c9300-3fd2-11ea-832b-46392c54df90.jpg)

Test with this save.
[test.zip](https://github.com/bvschaik/julius/files/4112235/test.zip)

**Comment by crudelios** [comment]
This one is an easy fix.

For my own reference, or if someone else wants to submit a PR (I have no access to a computer right now), it's a matter of checking for the city type instead of the expanded object's image id around line `302` to `318` of `src/window/empire.c`.

Since this doesn't affect savegames, I think it should be fixed even though it is original.

**Comment by bvschaik** [comment]
It's actually a problem within the .emp files, but fixing this was indeed easy.
