### ISSUE TITLE
Cam reacts minimap's only clicks

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#280]
![image](https://user-images.githubusercontent.com/46932541/73175526-13c3bb00-4113-11ea-9e1f-469e7ccb7c4a.png)

Camera only reacts on click on minimap, but doesnt react on cursor pulls. I mean, when we click on minimap and we HOLD mouse button clicked, and move cursor to another point in minimap, its good to camera moves with the cursor moves, while mouse button is still holded as clicked. (my english...)

**Comment by 411752230** [comment]
I do remember this feature was de-implemented by @bvschaik for some certain reasons.

**Comment by bvschaik** [comment]
Yes, it was implemented, but I reverted the change because there were two problems with it:

1. The way the isometric tiles are set up: if you move the mouse straight up or down, the city view will jump left one tile every pixel, and jump right every other pixel, leading to a jittery experience
1. Scroll: if your first click causes the minimap to scroll, the second frame it jumps to the new position below the mouse, and so forth until it stabilizes at the edge of the map, where you probably did not intend to go

The second one was a deal breaker and the reason I removed it. I see no way to implement this properly.
