### ISSUE TITLE
Map Editor , Emperor Change and Trade

### ISSUE THREAD

**Issue by Legionary2** [bvschaik/julius#283]
Hello everyone ! 
First question : I know from years of map editor use that the Change of Emperor function was suppose to revert favor back to 50 but never seemed to work properly. It’s a minor issue but was wondering if anyone was willing to make it work as intended ? 

Second question : I noticed in the editor , there is now a great option for demand changes which was in the original campaign. One other function which was in the original campaign was the delayed opening of trade routes, meaning an empire city which was already present now became a possible trade partner. Is there a possibility that a route can be delayed and opened on a set date by the player rather thank automatically available from the beginning ?

Third question : Caught the new warehouse option , which is a great addition. Is there a chance in the future will see a accept 1/4 option , 1/2 option etc for goods so that one good doesn’t overflow the warehouse.

**Comment by ArtySh0ck** [comment]
Julius aka Pharaoh edition ) but idea is still good

**Comment by bvschaik** [comment]
Hi!

I'll look into the Emperor change functionality.

Trade routes: the way the empire map works is that it has two states: the starting state, and the "expanded" state after an empire expansion event. The problem with those empire maps is that they are pre-defined in the `c32.emp` file, and none of the empire states has an "expanded" state with more cities.

Warehouses: unfortunately not without defining a new savegame format (and thus breaking compatibility with C3), because the storage buildings do not have any bytes available to store that data.

**Comment by Legionary2** [comment]
Thanks for the reply. I see why its tough for the trade feature - no worries.

**Comment by Legionary2** [comment]
> Hi!
> 
> I'll look into the Emperor change functionality.
> 
> Trade routes: the way the empire map works is that it has two states: the starting state, and the "expanded" state after an empire expansion event. The problem with those empire maps is that they are pre-defined in the `c32.emp` file, and none of the empire states has an "expanded" state with more cities.
> 
> Warehouses: unfortunately not without defining a new savegame format (and thus breaking compatibility with C3), because the storage buildings do not have any bytes available to store that data.

Hi! With some of the new editor changes , was the change of emperor not possible or was something weird with it that it couldn’t make it into 1.3?

**Comment by bvschaik** [comment]
I decided not to fix this for now since there might be scenarios out there that rely on the favor _not_ being reset. Perhaps I should add another option to the configuration screen for fixing the emperor change event, and perhaps also for fixing the time limit / survival time win criteria - those do not work if you have other win criteria set up.

**Comment by Legionary2** [comment]
> I decided not to fix this for now since there might be scenarios out there that rely on the favor _not_ being reset. Perhaps I should add another option to the configuration screen for fixing the emperor change event, and perhaps also for fixing the time limit / survival time win criteria - those do not work if you have other win criteria set up.

I see. I would appreciate if it was looked into when you get a chance. One of the win / lose criteria should be something sort of where you play the province for a set period of time + achieve the winning criteria? So players can experience the twist and turns of the province and not rush to victory right aaay

**Comment by bvschaik** [comment]
> I see. I would appreciate if it was looked into when you get a chance. One of the win / lose criteria should be something sort of where you play the province for a set period of time + achieve the winning criteria? So players can experience the twist and turns of the province and not rush to victory right aaay

It's on my to-do list, that's why I left the issue open. Regarding the survival time: yes, that's what I had in mind: play for a set period of time AND achieve the winning criteria. Right now the survival time only works properly when you don't have any other criteria set. Be aware that this will only work for people playing with Julius, and with a config option enabled.

**Comment by bvschaik** [comment]
@Legionary2 Both emperor change and survival time have been fixed, could you give [this build](https://bintray.com/bvschaik/julius-branches/windows/emperor-change-survival-time-fixes-1.3.0.25-f58c56b3#files) a go and see if it works properly when you have the new config option checked?

**Comment by Legionary2** [comment]
> @Legionary2 Both emperor change and survival time have been fixed, could you give [this build](https://bintray.com/bvschaik/julius-branches/windows/emperor-change-survival-time-fixes-1.3.0.25-f58c56b3#files) a go and see if it works properly when you have the new config option checked?

Will check now !

**Comment by Legionary2** [comment]
> @Legionary2 Both emperor change and survival time have been fixed, could you give this build a go and see if it works properly when you have the new config option checked?

Both changes work. I played a quick custom, setting ratings to 1 and pop to 100 with 2 winning years. I had the proper ratings the first year - victory didn't come until the second. All good.

**Comment by bvschaik** [comment]
Thanks for testing!
