### ISSUE TITLE
Bug with Caesar 3 1C russian version

### ISSUE THREAD

**Issue by MarkusCicero** [bvschaik/julius#292]
A small bug in displaying an era.
When the game date is BC, it displays correctly.
![01](https://user-images.githubusercontent.com/60564622/73604709-b7a3df80-45c7-11ea-960a-8e13dbedbb28.jpg)
But when the date is AD, then the display is not true.
![02](https://user-images.githubusercontent.com/60564622/73604711-ba9ed000-45c7-11ea-8d07-dda8de691f5b.jpg)

**Comment by ArtySh0ck** [comment]
наоборот, до рождения христа вылазит за границы, а после нормально. просто поменять местами год и н.э., так?

---- 
he wants to swap places of era name and current year when its A.D.

**Comment by MarkusCicero** [comment]
да верно, поменять местами

**Comment by ArtySh0ck** [comment]
in 1C ver. (rus.) era indicator stands after current year (100 BC) when it BC, but when its AD era indicator stands before current year - AD 100. Would be better if era indicator stands AFTER years always, in any case. Thanks

**Comment by bvschaik** [comment]
@ArtySh0ck Thanks for translating, since I can't read Russian I had no idea what the report was about.

I'll have a look. This is not a matter of simply swapping the year and era, because it will then be swapped for ALL languages. And then the other languages will be incorrect.

**Comment by ArtySh0ck** [comment]
so, actualy, its not so important to fix. this is just visual discomfort, but not annoyng

**Comment by crudelios** [comment]
So I've checked this out and apparently this is done on purpose:

https://github.com/bvschaik/julius/blob/8287b7036695582ad001f1f01f46375a920f3cb2/src/graphics/lang_text.c#L80-L91

This is because the inversion of year and `a.D` is a specific quirk of the english language.

From https://brians.wsu.edu/2016/05/16/a-d/:

> Traditionally “A.D.” was placed before the year number and “B.C.” after, but many people now prefer to put both abbreviations after the numbers.

This, however, is NOT the case for any other language. And since it's not mandatory in english, I suggest always puting `a.D.` or `b.C.` after the year.

**Comment by bvschaik** [comment]
This has now been fixed for Russian. I'll check the other languages later to see what the original C3 versions do.
