### ISSUE TITLE
Support Korean Language

### ISSUE THREAD

**Issue by fetchinist** [bvschaik/julius#295]
Hello. I am very happy to know this project as an old school gamer!

In the Korean version, the letters are not displayed properly and are shown as follows.

![q](https://user-images.githubusercontent.com/10090909/73656078-b7443b00-46d2-11ea-9aa7-b3b139ffa672.png)
![w](https://user-images.githubusercontent.com/10090909/73656095-bdd2b280-46d2-11ea-96dd-652b4b3eaa34.png)

Read other similar issues and upload files that you may need for your work.

[C3.zip](https://github.com/bvschaik/julius/files/4148053/C3.zip)

**Comment by 411752230** [comment]
Good to see you! I was one same as you who looks into supporting Chinese

**Comment by fetchinist** [comment]
Nice to meet you! It's a great pleasure to remember the old games together!

**Comment by bvschaik** [comment]
Thanks! I will have a look this evening. I may need additional files but I can't say which until I've had a look how the characters are handled.

For reference, could you also post a screenshot of how things normally look like in Caesar 3?

**Comment by fetchinist** [comment]
Thank you! Here's a screenshot that looks normal:

![q](https://user-images.githubusercontent.com/10090909/73671340-182d3c80-46ee-11ea-82eb-bad301eb5410.png)
![w](https://user-images.githubusercontent.com/10090909/73671357-224f3b00-46ee-11ea-8a64-c61a5a781e8c.png)

**Comment by bvschaik** [comment]
I've looked into this. The Korean .exe uses WinGDI to draw the Korean characters, and on my English version of Windows it apparently lacks a font or codepage or something so I only get dots.

WinGDI is not cross-platform so I have to think about how to add support for this. Probably I'll do something similar to the Chinese version: adding a new graphics file containing the characters. That will take a while though.

**Comment by fetchinist** [comment]
That's okay! If I can play games in my native language, it doesn't matter if it takes time. Thank you!

**Comment by 411752230** [comment]
> I've looked into this. The Korean .exe uses WinGDI to draw the Korean characters, and on my English version of Windows it apparently lacks a font or codepage or something so I only get dots.
> 
> WinGDI is not cross-platform so I have to think about how to add support for this. Probably I'll do something similar to the Chinese version: adding a new graphics file containing the characters. That will take a while though.

Cool! Creating a new rome555 for Korean?

**Comment by bvschaik** [comment]
@fetchinist I've started working on Korean support. To install the test build:

- Download [this test version of Julius](https://bintray.com/bvschaik/julius-branches/windows/korean-1.3.1.41-05d3ff47#files), extract the contents to your Caesar 3 folder
- Download [this Korean font file](https://github.com/bvschaik/julius/files/4309025/korean.zip), also extract the contents to your Caesar 3 folder
- Run julius.exe

Things that do not work yet:
- Word wrap: long lines will break at any character now
- Typing in Korean will not work
- The window title will say "III" instead of "시저 III"

Questions:
- In Korean Caesar 3, can you type Korean characters in any input fields, for example the load/save game dialog, or is it restricted to the Latin alphabet?
- Have the citizen's speech files, mission briefing audio and videos also been dubbed to Korean or are they still in English?

Any bugs, comments, feedback is very much appreciated!

---

Also, I've looked into the language files and there are a couple of English texts still in there. Could you perhaps translate those so I can put them in the language files?
- `Parts of your city are boxed in`
- `People living there will soon perish`
- `Data limit reached - see readme`
- `You have turned the effects of the gods OFF. So although they may get angry or pleased they will not show it.`
- `Security Buildings`
- `Date Display`
- `Distant battle`

Some incompletely translated messages:
- `로마에 대항하는 적들이 당신의 도시 외곽에 도착했습니다. Expect them to drop in for an urn or two of wine - and whatever else strikes their fancy!`
- `로마 내의 권력 투쟁으로 인해 이전 황제가 권좌에서 물러났습니다! 원로원은 회의를 열어 새로운 황제를 선출했습니다. Long live the Emperor! (Let us hope that he approves of his predecessor's governors.) Hail Caesar!`
- `도시 내의 위생상태가 좋지 않아서 질병이 발생했지만, 유능한 병원 근무자들이  your well-staffed hospitals have the outbreak under control.`
- `전염병이 발생했습니다! 병원들이 감당하기에는 환자들이 너무 많습니다. They have ordered the fumigation of parts of the city.`

**Comment by fetchinist** [comment]
Wow, Thank you! It feels new to see the game in Korean at high resolution!

---

Answers to the questions:

- In Korean Caesar 3, can you type Korean characters in any input fields, for example the load/save game dialog, or is it restricted to the Latin alphabet?

> When entering the name of the new governor, ?? is entered and nothing is entered when enter a name for the saved file.

- Have the citizen's speech files, mission briefing audio and videos also been dubbed to Korean or are they still in English?
> It is not dubbed in Korean. It's only in English.

---

Next, please understand that Korean translation may not be accurate because I am not good at English.

- Parts of your city are boxed in
> 당신 도시의 고립된 부분

- People living there will soon perish
> 그곳에 사는 사람들은 곧 목숨을 잃을 것입니다

- Data limit reached - see readme
> 데이터 한도 도달 - 읽어보기를 보세요

- You have turned the effects of the gods OFF. So although they may get angry or pleased they will not show it.
> 신들의 영향을 껐습니다. 신들이 화를 내 거나 기뻐하더라도 영향을 보여주지 않을 것입니다.

- Security Buildings
> 보안 건물

- Date Display
> 날짜 표시

- Distant battle
> 원거리 전투

- 로마에 대항하는 적들이 당신의 도시 외곽에 도착했습니다. Expect them to drop in for an urn or two of wine - and whatever else strikes their fancy!
> 로마에 대항하는 적들이 당신의 도시 외곽에 도착했습니다. 그들이 항아리나 포도주 둘, 아니면 필요한 무엇이 되었든지 얻어 내기 위해 잠시 들를 것입니다!

- 로마 내의 권력 투쟁으로 인해 이전 황제가 권좌에서 물러났습니다! 원로원은 회의를 열어 새로운 황제를 선출했습니다. Long live the Emperor! (Let us hope that he approves of his predecessor's governors.) Hail Caesar!
> 로마 내의 권력 투쟁으로 인해 이전 황제가 권좌에서 물러났습니다! 원로원은 회의를 열어 새로운 황제를 선출했습니다. 황제여 영원하여라! (우리는 새로운 황제가 이전 황제의 통치자들을 인정하길 바랍니다) 시저 만세!

- 도시 내의 위생상태가 좋지 않아서 질병이 발생했지만, 유능한 병원 근무자들이 your well-staffed hospitals have the outbreak under control.
> 도시 내의 위생상태가 좋지 않아서 질병이 발생했지만, 유능한 병원 근무자들이 발병을 잘 통제하고 있습니다.

- 전염병이 발생했습니다! 병원들이 감당하기에는 환자들이 너무 많습니다. They have ordered the fumigation of parts of the city.
> 전염병이 발생했습니다! 병원들이 감당하기에는 환자들이 너무 많습니다. 병원에서 당신의 도시 일부를 훈증 소독하라고 요청했습니다.

**Comment by fetchinist** [comment]
I didn't check the whole thing, but it's perfect!

Because Korean changes the line by syllable, there is no problem reading it even if it is displayed as it is now. You don't have to work on it.

Other than the lettering in the date display section, it doesn't look like anything else is wrong with me at the moment!

![q](https://user-images.githubusercontent.com/10090909/76318176-a796c280-6320-11ea-9967-12d4106f6962.png)

**Comment by crudelios** [comment]
@fetchinist Can you show how the original C3's date section looks like in Korean, please?

**Comment by fetchinist** [comment]
I checked again, and the original game is also the same as the character being out of bounds.

![w](https://user-images.githubusercontent.com/10090909/76320200-a9ae5080-6323-11ea-9381-be6b7d91f8d7.png)

**Comment by crudelios** [comment]
Thanks.

**Comment by bvschaik** [comment]
@fetchinist Thanks for the answers and new translations, I'll update the language files tomorrow. And thanks for testing! One thing I wonder about: do links work properly in the help pages? That's something we had trouble with when implementing Chinese.

And regarding the date: it runs out of bounds in multiple other languages as well. I'll see if I can enlarge the box a bit.

**Comment by fetchinist** [comment]
Yes, it works very well!

![eb6ace5c9f7f](https://user-images.githubusercontent.com/10090909/76397828-25111000-63bf-11ea-93fa-102d32c19cae.gif)

**Comment by bvschaik** [comment]
Thanks! Korean support is now available in the regular development builds of Julius.

You can get the updated language files and the font file [here](https://bintray.com/bvschaik/caesar3-patches/korean).

**Comment by fetchinist** [comment]
Thank you very much!
