### ISSUE TITLE
Don't show all extra sidebar info on the tutorial missions?

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#326]
The extra info panel is very helpful, however I feel that the ratings and unemployment info look weird on the first two missions where you don't have access to your advisors.

So perhaps, while they are not available, we should display `Not available for this assignment` and `Not available... Yet` below `Ratings` and next to `Unemployment`?

I think it would make the game a little bit more consistent.

**Comment by m-mohr** [comment]
Agreed. Maybe don't show them at all? So just show what is available?

**Comment by crudelios** [comment]
> Maybe don't show them at all? So just show what is available?

That's also a possibility, and actually easier to implement.

**Comment by bvschaik** [comment]
If we implement anything, it should be quick enough to not slow down the game since it will be executed 60 times per second. Simply hiding the information should be sufficient.

On the other hand: I also see no problem with leaving that information there for the first two missions. For Brundisium, the advisors become available anyway when you reach 250 people. In the first mission the ratings don't matter, but employment could be handy.

**Comment by crudelios** [comment]
This is all really a detail that I found, so no problem in keeping as is.

In terms of extra execution, a simple `if` should do the trick so it isn't too intensive.

**Comment by bvschaik** [comment]
Then we keep it as-is 😃
