### ISSUE TITLE
sound is crackly

### ISSUE THREAD

**Issue by sketchbuch** [bvschaik/julius#346]
There seem to be a lot of noise/crackling when the game first starts behind the music

**Comment by CommonLoon102** [comment]
You mean the credit videos after you start the game? That is how the game originally sounds, it is how it was recorded. It is the same in the original game, no bug here.
Or you mean something else?

**Comment by bvschaik** [comment]
Could you tell us a bit more about where exactly you hear the noise/crackling? When you're on the main menu, when you just load a city or somewhere else?
And which platform/operating system are you running on, with which version of Julius?

**Comment by bvschaik** [comment]
I'm going to assume the crackly/noisy sound is because the crackle/noise is actually in the .wav file. There's no way we can fix that in Julius.

If that's not the case and the sound is clear when played in an external player, please comment on this issue with more information and we can take a look.

**Comment by NerosTie** [comment]
He is right. Tested with the MP3 files, the music is crackling a lot. It's not the case with Julius.
