### ISSUE TITLE
Oracle can be made to have garbage texture

### ISSUE THREAD

**Issue by theradeonxt** [bvschaik/julius#347]
Hi, 

I made a map and started to play it. 
At some point I found a weird behavior with an Oracle where it's missing the image.
I gave a try with original game and it's the same problem. 
Then tried to re-load the save game - it happens again (even fullcreen/window mode is the same).

**Found with:** julius 1.3.0

**Steps to reproduce (potential):**

1. Added oracle
2. Added wall by accident in a random location
3. Rotated map
4. Clicked Undo
5. Got this weird "missing texture" and steals adjacent buildings texture:

![Capture](https://user-images.githubusercontent.com/13402104/75046476-d235ee00-54cd-11ea-99ab-8baeab3ca5ab.PNG)

But if I rotate map it shows indeed an Oracle:

![Capture3](https://user-images.githubusercontent.com/13402104/75046547-f7c2f780-54cd-11ea-820e-516a96c5b406.PNG)

**Save game:** (custom created map) 
[IslandFort-41bc.zip](https://github.com/bvschaik/julius/files/4236690/IslandFort-41bc.zip)

**Comment by bvschaik** [comment]
Whoa. It's not a problem with the oracle, it's a problem with building walls... you can build them on top of about everything, even though the red footprint indicates you can't! In your case you apparently placed the wall on top of the oracle. Good find.

I just checked and this has been present since at least 1.1.0, so I guess it's been in here since the start. I'll have a look.

In case of your savegame: it's now corrupted, so the only way to fix it is deleting the oracle and rebuilding it.

**Comment by theradeonxt** [comment]
Haha it accidentally placed it on top of Oracle.
I can fix it the way you describe.
Thanks for the fix!
