### ISSUE TITLE
Unit limit release patch

### ISSUE THREAD

**Issue by unison12** [bvschaik/julius#369]
I'm pulling for your Caesar 3 remake project.

There is already a Unit limit release patch.

How is it reflected in the project?

http://caesar3.heavengames.com/cgi-bin/caeforumscgi/display.cgi?action=ct&f=9,7624,,20

https://www.reddit.com/r/impressionsgames/comments/1qq5vw/caesar_iii_recap_on_building_and_walker_limit/?st=isgx2v2y&sh=cf26b8d9

**Comment by bvschaik** [comment]
Thanks for your interest.

The goal of Julius is to maintain full compatibility with Caesar 3's savegames. Increasing building/walker/route limits will cause savegames to crash in Caesar 3, so that why it won't be implemented in Julius.

Keriew's fork [Augustus](https://github.com/Keriew/julius) was planning to increase the limit, though I don't know what the current status is.
