### ISSUE TITLE
Rubble: Nowhere ... ?

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#397]
If something burns out or crashes it leaves a Rubble, u know. Originaly, when we right-click that rubble we can read what kind of building this was before accident. But now it's "Nowhere" even when i have NOT load a savegame. I mean i see "Nowhere" on info screen of Rubble right after accident... and have no way to know which building i need to re-build here =(

I try this on latest unstable - 1.3.1.64 with my english and russian version both.

PS: By the way... great thank for new russian fonts, its AMAZING to read =)

**Comment by bvschaik** [comment]
I'll have a look, it should still work. Was the rubble caused by fire, collapse, invading enemies or a blocked road to Rome?

**Comment by bvschaik** [comment]
I just tested it: the only way I can get the "nowhere" to show up on rubble, is if enemies destroy a wall, since a wall is not officially a "building". Any other rubble, from collapse, fire, or blocked road to Rome, all correctly display the building it previously was.

Can you confirm it was a wall destroyed by enemies in your case? If so, I have a fix ready.

**Comment by ArtySh0ck** [comment]
i need to recheck this.
