### ISSUE TITLE
Any plan to remove building and walker limit?

### ISSUE THREAD

**Issue by theodoretsai** [bvschaik/julius#414]
Hi,

In my personal experience most of the games are forced to end with data limit reached warning when reaching ~16.000 population since I play on the window version, is there any plan to address the issue? There are mods out there but they cannot be used simultaneously with Julius.

Thank you.

**Comment by crudelios** [comment]
This will not be done on Julius itself since it breaks savegame compatibility with the original C3 save files. Julius' goal is to retain 100% savegame compatibility.

However, the limits are being increased in [Augustus](https://github.com/keriew/julius) (a fork of Julius which adds features that break savegame compatibity) and will be available on its next release.

**Comment by theodoretsai** [comment]
Thank you very much, will be waiting for the update.
