### ISSUE TITLE
Upscaling the snk videos

### ISSUE THREAD

**Issue by jonathanmcnamee** [bvschaik/julius#429]
If it was possible to convert the smk videos to a modern format (MP4/bink?) and upscale them, would it be possible/suitable to replace the originals just like the mp3s?

**Comment by NeoXaero** [comment]
I've done that already, but the game doesn't support mp4s, and also it's illegal to distribute the video files alongside the julius project, so @bvschaik declined my offer.

**Comment by bvschaik** [comment]
With enough time and effort basically anything is possible, but there are two main reasons I don't want to replace the videos:

1. Copyright issues. Upscaling an existing video and then distributing them violates copyright of the game assets. Something I really don't want to do. For the MP3 files this was different, since those were already made available by Impressions/Sierra.
2. Integrating video codecs is a pain in the ass technically, especially getting the performance right on lower-end devices, like the Vita and Switch. For the current Smacker videos, I finally got them working nicely by writing my own custom codec for them, an exercise I don't want to repeat for more complex codecs like MP4.

Another reason: most of the videos would not benefit from upscaling anyway, since they're displayed in the message window, which has a fixed size.
