### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by hathlife** [bvschaik/julius#435]
Describe your improvement here.
Keep in mind that UI improvements which require new texts will most likely be declined because we can only work with the original text files. Also, large UI changes will not be accepted.
It seems that twos thing can be dealt with SDL2，like AOE2DE:

- [ ] HiDPI support (Currently the program only report 1536x384 resolution when system setting is 3840x2160 with 250% scale on Win10;

- [ ] Camara zoom-in.

**Comment by crudelios** [comment]
There is scaling support by adding `--display-scale X`, where `X` is a value between `0.5` and `5`.

For zoom, it will be added to Augustus :+1:

**Comment by hathlife** [comment]
> There is scaling support by adding `--display-scale X`, where `X` is a value between `0.5` and `5`.
> 
> For zoom, it will be added to Augustus 👍

It seems that adjusting --display-scale arg just scale the whole screem output, not I really wanted.
![2020-05-06](https://user-images.githubusercontent.com/19867269/81135405-9ff34300-8f8a-11ea-981b-c8399db28ac3.png)

what I want is the UI scaling, at least, smoother text.

**Comment by crudelios** [comment]
Since text is based on image files (and not on fonts) and the ui images have a fixed size and the entire ui code is hardcoded into the executable, it's not possible to achieve a true hi-dpi look, short of rewriting both all the images and the entire graphics code for Julius.

So it don't be done.

For camera zoom in/out, as I said, expect that in Augustus in a not too distant future.

**Comment by crudelios** [comment]
In a related not, camera zoom has been added to Augustus today and will be available on the next release.
