### ISSUE TITLE
Warehouse can't GET more than 8 units of pottery

### ISSUE THREAD

**Issue by Dgeremi** [bvschaik/julius#458]
Hi, 
STR: 
Build 2 warehouses not connected with road
Fill one of them with pottery 
On the second one mark pottery as "getting" 

Expected result:
Second warehouse filed with pottery from the first warehouse

Actual result:
Only 8 units were get from the first warehouse after that it stopped getting pottery

Attaching savefile of my custom map. Also attaching screenshot, playing on Russian versio but we can see in the second warehouse that it is "waiting for orders" but it should getting pottery from first warehouse

P.S. I've also reprodused such behavior with furniture
Other goods seem ok, Oil requires testing.

![warehouse-issue](https://user-images.githubusercontent.com/12035588/82243825-ea8c9c00-9948-11ea-9636-5938aba23898.jpg)
[warehouse-issue.zip](https://github.com/bvschaik/julius/files/4645688/warehouse-issue.zip)

**Comment by bvschaik** [comment]
Actually, this behaviour is also present in Caesar 3: if a warehouse has 4 or fewer of a resource, it will send out a cartpusher to get a further 4 loads, so in total it has 8. If it has 5 or more, it will not get any more.

Since it also works like this in Caesar 3, and Julius does the same, I'm closing the issue.

**Comment by crudelios** [comment]
I believe this has been fixed in [Augustus](https://github.com/Keriew/julius).
