### ISSUE TITLE
Pause music and sounds when the game is minimized

### ISSUE THREAD

**Issue by agruzdev** [bvschaik/julius#465]
P.S. Can try to implement myself

**Comment by crudelios** [comment]
Actually, pausing the whole game (not just the sounds) while minimized would be nice!

If you want to implement it yourself (we are rather short on time right now), beware as it requires interaction between SDL and many game elements, and we are quite strict about where SDL code can be used in the project.

**Comment by agruzdev** [comment]
Sorry then, can't promise any deadlines, due to my main job to do as well
I considered it as a nice feature to think about in free time

**Comment by crudelios** [comment]
No problem, this will stay here until it's adressed.

**Comment by bvschaik** [comment]
It's a 'nice to have' so don't worry about time :)

I tried to implement this way back in the day when Julius still used SDL 1.2 and I gave up.
Some things to keep in mind:
- There's a difference between the game actually being minimized and the game being in a window that no longer has focus. Some operating systems / desktop environments don't truly support minimizing windows.
- We have a bit of a hack to make fullscreen scrolling work on HiDPI screens in Windows because there's a subpixel that's not truly part of the window, that should still work (see scroll.c).

**Comment by ArtySh0ck** [comment]
this feature could be as option in Options Menu. as a checkbox "Mute sounds and music when minimized".

**Comment by bvschaik** [comment]
I tried it out on Mac and Windows:

- Mac receives a `minimized` and `hidden` window event when using the orange minimize button, just a screen resize when maximizing using the green button, and only a `shown` event when it's restored from minimized state - no `restored` event.
- Windows receives a `minimized` window event when minimizing, `maximized` when maximizing, and `restored` when restoring. No `hidden` or `shown` events.

I didn't test Linux just now, but I fear it's going to be a mess. I certainly want to prevent the user getting stuck with no sound and no running game when performing a specific sequence of window actions.

**Comment by crudelios** [comment]
This issue has been here, gathering virtual dust, for a while.

Should we implement this? If so, we need to hack a consistent way to detect window minimization/restoration across different platforms.

Otherwise we should just close the issue without actually implementing it.

**Comment by bvschaik** [comment]
I was also thinking about it this morning. I find it pretty scary to "pause" the game on certain SDL events: there are so many ways in which this can break, because the event system is not consistent across platforms.

So with that in mind I'm closing this issue as wontfix.
