### ISSUE TITLE
Current Year/Month in Imperial Map

### ISSUE THREAD

**Issue by ArtySh0ck** [bvschaik/julius#482]
Oftenly i went to see Imperial Map to know how much marble i sold this year far, and how much iron i bought in this year far. I see 8/25, 10/25, but i forget to see current date before imperial map... and i forget and i forget, this thing repeats everytime. Today was a last straw... maybe some current Date in Imperial Map? There is a lot of free space, a lot of. Thanks!

![yo-leo-what-month-of-the-year-is-it](https://user-images.githubusercontent.com/46932541/84209100-e1ad6700-aabd-11ea-8992-aa4d16716d1e.png)

**Comment by crudelios** [comment]
But... The current implementation adds to the mystery of the game, allowing it to keep the suspenseful nature we've come to love: "will the market lady turn right at the intersection, towards the houses that desperately need food... or towards the left, which only has industry?" (Disclaimer: of course the market lady will turn left!)

Other than that, apart from little spacing at 640x480 resolution, I guess we can find a spot to add the current date.

**Comment by ArtySh0ck** [comment]
we could consider this one as option in Julius Configuration Menu?
- Show current Month/Year on Imperial Map [ x ] / [   ] // or something?

**Comment by bvschaik** [comment]
To be honest I don't think adding a date to the empire map makes sense. Yes, it may be handy, but how hard is it to glance at the date before entering the empire map? Or just look at the trade numbers, return to the city where you have the month available and then do the "oh, I still have half a year left to sell 15 marble" thinking. Besides that, there's nowhere to put it where it a) doesn't overlap with other texts, and b) it doesn't look out of whack with the rest of the UI.

I don't want to add configuration options for every little UI change, since the list is already getting long - I just had to implement a scrollbar there...
