### ISSUE TITLE
Navigation impossible message

### ISSUE THREAD

**Issue by SzKrisz22** [bvschaik/julius#495]
Does anybody know, how to trigger the 'Navigation impossible' message?
(When the ships can't reach the docks, because of low bridges)
I found that message in the c3_mm.eng file, tried triggering it, but failed in the original game too.
Maybe it was patched and left in the eng file.
Is there a chance of reimplementing it?
(Now I get no working dock, or no message at all.)

**Comment by bvschaik** [comment]
The message is in the code: if a trade ship somehow gets stuck you get this message.
But I haven't found a way to trigger that yet... if the dock is unreachable because of low bridges, no trade ship appears but you do get a "no working dock" message after a year. If you build a low bridge while a trade ship is sailing in, it will sail right through the low bridge, and disappear when it's done at the dock.
I'll see if I can replace the "no working dock" with "navigation impossible" if there *is* a dock with employees in the city.

**Comment by bvschaik** [comment]
I looked into it: properly implementing the message requires either a change in the saved game format to record the number of working-but-not-connected-to-open-water docks (unacceptable) or a fairly expensive loop through all buildings every time a trader is created (also unacceptable). So unfortunately we won't reimplement it.

**Comment by SzKrisz22** [comment]
Oh, OK.
Maybe, if the sea traders wouldn't pass through the low bridges, the implemented method would get triggered. But this could cause stuck traders...
