### ISSUE TITLE
Bugs for the Simplified Chinese translation

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#507]
Notes of the "official" Simplified Chinese translation

1.档案 rather 档盎
![QQ截图20200717081332](https://user-images.githubusercontent.com/14128007/87734563-8cbfe780-c805-11ea-9086-e659d41ddf5d.jpg)

_Originally posted by @411752230 in https://github.com/bvschaik/julius/issues/192#issuecomment-659748087_

**Comment by 411752230** [comment]
Texts needed to be translated
> C3.eng: string groups 150, 151, 152
> C3_mm.eng: messages 331-345

Originally posted by @bvschaik

**Comment by 411752230** [comment]
神灵效果 rather than 神只效果
![QQ截图20200718205641](https://user-images.githubusercontent.com/14128007/87853041-8b8fd700-c939-11ea-9bc2-669f1eba87ec.jpg)

**Comment by 411752230** [comment]
Perversion among three dialog texts
1.'Exit the game or not' rather than 'pay money to open the trade route'
![QQ截图20200718205016](https://user-images.githubusercontent.com/14128007/87853148-72d3f100-c93a-11ea-85e7-1adcd9cea326.jpg)

2.'pay money to open the trade route' rather than 'Dispatch goods?'
![QQ截图20200718205037](https://user-images.githubusercontent.com/14128007/87853167-9139ec80-c93a-11ea-911e-7924f3a6044b.jpg)

3.

**Comment by 411752230** [comment]
Bad descriptions
![QQ截图20200723021048](https://user-images.githubusercontent.com/14128007/88212374-c1aabf00-cc89-11ea-9e02-af88185c0f11.jpg)

**Comment by 411752230** [comment]
Mismatched chars in different font sizes - Found by @bvschaik
案 -> 盎
按 -> 胺
岸 -> 肮
阿 -> 暗
奥 -> 哎
艾 -> 隘
啊 -> 挨
昂 -> 敖
昂 -> 敖
 III -> V

**Comment by bvschaik** [comment]
All issues are fixed in the [patched files](https://github.com/bvschaik/julius/wiki/Patches) for Simplified Chinese.
