### ISSUE TITLE
Wineskin issue

### ISSUE THREAD

**Issue by vhologram** [bvschaik/julius#508]
How does one go about playing the julius patch of caesar 3 using wineskin winery on macOS High Sierra? The vanilla version of the game runs perfectly using wineskin but it keeps telling me I don't have the proper folder for Caesar 3 when I try to run julius.exe in a separate wrapper.

**Comment by bvschaik** [comment]
It's better not use the Windows julius.exe on a Mac, since there's a [native julius.app](https://bintray.com/bvschaik/julius/mac/_latestVersion#files) version for Mac available that will offer better integration with your Mac.

When you first start Julius.app, it asks for your Caesar 3 folder. You'd have to find out where Wineskin stores its files and choose that directory in the dialog.

If you insist on using the Windows executable, it'll have to be in the same wrapper as c3.exe. Running julius.exe in a separate wrapper will not work because it cannot see anything outside of its own wrapper.

**Comment by vhologram** [comment]
I can't get the Julius.app to work. I can't seem to find the Wineskin files in the dialog. I created a separate wrapper but it tells me that it isn't a proper caesar 3 folder when I select it in the directory. I get the same message when trying to run julius.exe. What is the correct way to install the game with the patch?

**Comment by vhologram** [comment]
Thank you for your help.
