### ISSUE TITLE
Add "Don't show again" to "Wrath of God" dialogs.

### ISSUE THREAD

**Issue by onurarpapay** [bvschaik/julius#522]
In some levels, we intentionally choose to neglect one god, for example in Lugdunum I don't need Neptun and in Tarsus Ceres isn't necessary. Neglected god sends his/her wrath upon us and we get informed about this in a dialog with a nice video. But it gets repetitive and pointless if we KNOW that we neglected that god and we are OK with the disaster they send to us.

An e.g. "Don't inform about this disaster again" option would be beneficial and support the gameplay. 
Edit: OR, the warning would be converted into a normal message like "employees needed", perhaps this would make more sense.

**Comment by bvschaik** [comment]
Thanks for the suggestion. However, this will not be implemented in Julius for the following reasons:
1. Adding an option requires adding new texts to the game, which is something we do not accept for the main game, particularly since we're currently supporting 12 languages and maintaining translations for all of them is troublesome.
1. Adding this option to the message dialogs is not possible since they cannot be enlarged while supporting 640x480 resolution.
1. Saving this option on a per-mission basis will break savegame compatibility.
1. I think this is a niche strategy that not many players use. Most players (including myself) will happily build temples to the "unnecessary" god.

This suggestion is more suited to Augustus.

**Comment by onurarpapay** [comment]
Thanks for the reply.
