### ISSUE TITLE
UI interaction when menu overlays are open

### ISSUE THREAD

**Issue by gergelypap** [bvschaik/julius#534]
I often find myself trying to "click away" after I opened the **Overlays** dropdown menu in the top right corner. My intuition based on modern software UIs tells that the Overlays menu should automatically close, and the new action should behave as expected.

Example:

1. Open Overlays menu.
2. Decide that you want build a house instead, click on house icon.
3. Nothing happens, because you first need to right click / escape out of the Overlays menu.

Also, scrolling is not possible when the Overlays is opened.

![image](https://user-images.githubusercontent.com/5883922/99384065-26d88f00-28cf-11eb-9f69-b73d0945f019.png)

I checked, and the original Caesar III has the same behaviour, however, this minor UI modernization would nicely fit into Julius. My proposal:

- Clicking any sidebar button or top menu item when the Overlays menu is open, should automatically close the Overlays menu and activate the clicked button.
- Scrolling when the Overlays menu is open should be possible.

What do you think?

**Comment by crudelios** [comment]
While I don't necessarily agree it should be possible to scroll the city while the overlays menu is open (after all, you're in a menu, not in the city), I do agree that clicking any other button should close up that panel.

However, due to the way the game is structured, it's not possible to easily implement such code. What's possible (and relatively easy) is to close the overlays menu if you left-click a certain distance away from it, thereby freeing you to click on another button.

**Comment by gergelypap** [comment]
As @bvschaik menioned on Discord, this overlay behavior applies to other menus, such as building buttons and the top menu bar as well.

**Comment by crudelios** [comment]
I've implemented this with an added feature: on the building menu, when a menu is opened, clicking on the same button for that menu will close it.
