### ISSUE TITLE
Building bridges should show the cost

### ISSUE THREAD

**Issue by gergelypap** [bvschaik/julius#541]
When building roads or reservoirs, dragging the mouse shows the cost of building:

![image](https://user-images.githubusercontent.com/5883922/99591330-ec661380-29ee-11eb-97bc-59d2968f7fa1.png)

![image](https://user-images.githubusercontent.com/5883922/99591396-03a50100-29ef-11eb-86ac-ac8134ca429d.png)

This is not the case with bridges:

![image](https://user-images.githubusercontent.com/5883922/99591285-db1d0700-29ee-11eb-97f2-8ef121f95898.png)

Bridges are quite expensive, taking 100 denarii per tile for a Ship Bridge, and 40 denarii for a Low Bridge, so I think it would be nice to see how much would it cost. The bridge in the picture costs 1400 for example.

**Edit:** I am now seeing that the cost is only shown when the mouse click is pressed and hold, for every building. I'm guessing this is the reason bridges don't show the cost, because they are not "draggable". However, I tend to now favor showing costs for all buildings even when just hovering the mouse and not clicking. Of course, I can "drag away" to see the cost and not build the bridge, but it is not really intuitive. 

What do you think?

**Comment by crudelios** [comment]
The reason most recent games always show the cost is because there is extra cost due to terrain inclination or tree removal, which doesn't really exist on C3.

In C3 the building cost is already shown on the menu, so we think it's distracting to always show it.

However, as you mentioned, the bridge is an exception. So we'll be implementing your idea for bridges.
