### ISSUE TITLE
Please enable GitHub discussions

### ISSUE THREAD

**Issue by felipecrs** [bvschaik/julius#570]
It would be good if we could leave the questions/tips separated from the real bugs or new features. I suggest you enable the GitHub discussions for this repository.

**Comment by bvschaik** [comment]
We thought about this: Julius itself is pretty stable and sort of "finished" now, since the project's goals of having a slightly more modern version of Caesar 3 are reached. We feel there's not much left to discuss in terms of functionality, and the few things that pop up can be handled through issues.

**Comment by felipecrs** [comment]
Alright :)
