### ISSUE TITLE
Change price units in Korean version

### ISSUE THREAD

**Issue by fetchinist** [bvschaik/julius#576]
I didn't notice because only Julius was playing, but in the original Korean version, the construction price unit is marked as 'Dn', but Julius is marked as a '자금'(funds).

in Original
![qwe](https://user-images.githubusercontent.com/10090909/104116608-5949ba00-535d-11eb-9c39-773bebb17acf.png)

in Julius
![asd](https://user-images.githubusercontent.com/10090909/104116610-64044f00-535d-11eb-8bb9-a4481e87776c.png)

**Comment by bvschaik** [comment]
A bit of history: originally, every language would use the fixed string "Dn". This was changed last year to use the string also used in the top menu so it's correct for most languages (#464). All languages besides Korean use the translated variant of "Dn" there, but apparently the Korean translators decided to use "Funds".

I've made an exception for Korean now, so it's fixed in the next build.
