### ISSUE TITLE
Carts stuck in granary after Mercury destroys it

### ISSUE THREAD

**Issue by felipecrs** [bvschaik/julius#577]
![image](https://user-images.githubusercontent.com/29582865/104492394-5398e200-55b2-11eb-8a15-c10fd3081f4c.png)

These 3 carts do not leave the place where the granary was. They say "Coming from wheat farm to Mercury temple": 

![image](https://user-images.githubusercontent.com/29582865/104492502-817e2680-55b2-11eb-95f5-f5dd5d35408e.png)

Save file:
[Granary Mercury cart bug.zip](https://github.com/bvschaik/julius/files/5810406/Granary.Mercury.cart.bug.zip)

**Comment by bvschaik** [comment]
You don't need to let Mercury destroy the granary: this also happens if you delete it yourself. The guys are stuck because there's no road connection to any other granary. They display "Temple to Mercury" because that happens to have the same internal building ID as the granary they were standing in. You can get them "unstuck" by building a road to them and having another granary accepting the goods they're carrying.

There's nothing we can really do to "fix" this: this situation is very hard to detect, and letting them disappear will cause their produce to be lost. This also happens in original Caesar 3, so I'm closing this as won't fix.
