### ISSUE TITLE
PS Vita joystick control regression

### ISSUE THREAD

**Issue by devnoname120** [bvschaik/julius#578]
Tested on e6c4441a51683095e34b4eeb09ee0875b151aa57 (latest master).

When I did the PS Vita port the joystick worked properly. But right now it has the following issues:
1) If smooth scrolling is disabled (which is the default), then it's really annoying to use. I think we should always use smooth scrolling for the joystick — just like we do for the touch screen.
2) It only supports 8 directions (4 dirs + 4 diagonals). This makes it worse for scrolling through the map. It used to scroll in the exact direction of the joystick — just like the touch screen.
3) (Opinion) It has a rubber / input lag feeling due to the fact we use the gradual scroll speed decrease — which was meant for touch I think.

**Comment by crudelios** [comment]
These are all fixed in the joystick support PR, I think...

**Comment by crudelios** [comment]
@devnoname120 now that #529 and #587 have been merged, can you please test?

**Comment by devnoname120** [comment]
Looks good to me!

The performance on big maps is pretty terrible though, especially when scrolling.
You can try this one if you have a PS Vita at hand: https://caesar3.heavengames.com/downloads/showfile.php?fileid=735

**Comment by crudelios** [comment]
Strange... brugle's palace peaks runs at 45-50 fps for me, and it has 86000 pop.

**Comment by devnoname120** [comment]
It runs at ~35 fps when scrolling but it feels super laggy.

**Comment by devnoname120** [comment]
It runs at ~50 fps on my original port.

**Comment by crudelios** [comment]
Strange.. what's your build number? It did run at 35fps before updating the vita sdk.

**Comment by devnoname120** [comment]
I've tested both https://github.com/devnoname120/julius/releases/tag/0.10 and https://github.com/bvschaik/julius/releases/tag/v1.1.0.

I wouldn't be able to say what's the most recent version that has this performance though. :(

**Comment by crudelios** [comment]
Did you test against [this build](https://julius.biancavanschaik.nl/download/julius-1.6.0.39-e0977bb5-vita.vpk)?

**Comment by crudelios** [comment]
@devnoname120 I did a comparison today between v1.1.0 and the latest build and found out that the choppiness only happens when smooth scrolling is enabled.

Since there was no smooth scrolling on v1.1.0, things don't feel as choppy as the viewport only changes every so often. In fact, if you disable smooth scrolling on the most recent builds, scrolling won't be choppy as well.

In terms of fps on Brugle-PalacePeaks, both were oscillating between 35-55 depending on the area, with no perceptible difference between them.

The only thing I can think about to improve scrolling performance when smooth scrolling is enable (and performance overall) is to overclock the vita to its maximum official clocks. That will net a 25% boost to performance at the cost of some battery life.

Other than that, since the controls now seem to be working properly, I'm closing this issue 👍
