### ISSUE TITLE
Cart pushers don't go to the near granary

### ISSUE THREAD

**Issue by mpmartimbianco** [bvschaik/julius#582]
Hello,

I have this save with my city where cart pushers have a weird behavior that I beliave it is a bug.

The city has two "blocks", on the first one, more to right (up to north) the cart pushers are ok, delivering wheat to the near granary, but on the second block they are ignoring the near granary and going to the far one.

The granary doesn't have any special orders, you can delete it and create a new one and this behavior still happens.

Can you help me understand why? Thanks.

[Valentia II.zip](https://github.com/bvschaik/julius/files/5925739/Valentia.II.zip)

**Comment by crudelios** [comment]
This is by design.

C3 (which Julius tries to follow strictly) considers whichever granary/warehouse is closest to the road to rome when factoring in the distance. In your case, since the north granary is closer to the road to rome and both granaries are relatively close to each other, the game considers it to be the best candidate for storing the goods.

Removing the "road to rome" factor improves that, but that's beyond the scope of Julius.
