### ISSUE TITLE
Brazilian Portuguese issues. 

### ISSUE THREAD

**Issue by saib4682** [bvschaik/julius#583]
Hello, I just downloaded and installed the 1.60 version for Windows. If I run the Julius.exe the songs AND the Instructor voice do no tplay at all. But if I run the C3.exe, the music plays correctly. Any ideas on how to fix that?

**Comment by crudelios** [comment]
What about videos and sound effects, do they work?

Also, do you have the 1.1 patch?

**Comment by saib4682** [comment]
Yes. Video configs work out fine. City sound effects and voices still work too.

**Comment by bvschaik** [comment]
I'm guessing you installed from CD? If so: Julius only supports full installations where all files are copied to your disk. If you did a minimal/standard installation, Caesar 3 will get the music and voice files from the CD; Julius doesn't know anything about CDs so that's the reason it can't play them.

**Comment by saib4682** [comment]
So I reinstalled it with the Max Installation and it worked out great. Thank you!
