### ISSUE TITLE
Sound stops after a few seconds

### ISSUE THREAD

**Issue by bvschaik** [bvschaik/julius#588]
Hi everybody! I happen to have almost the same problem with Augustus, the music in Caesar 3 splashscreen plays for like 2 seconds and then stops...no sound, no music no nothing. The game itself works just fine. I have the GOG version. Its the same with Julius. Reinstalled the game several times, tried whitelisting in Windows Defender and nothing works :/ I havent found topic with similar problem anywhere, so sorry if its innaprops here in advance. Thanks

_Originally posted by @Vlasta3000 in https://github.com/bvschaik/julius/issues/168#issuecomment-787107237_

**Comment by bvschaik** [comment]
@Vlasta3000 I've create a new issue since this appears to be something we haven't seen before.

Could you post the contents of "julius-log.txt"?

**Comment by Vlasta3000** [comment]
@bvschaik Ok, thanks for the reply. The log is here:
[julius-log.txt](https://github.com/bvschaik/julius/files/6056380/julius-log.txt)
Im using AMD high definition audio device, since Ive hdmi from  radeon rx 570 plugged to my TV and then earc to Yamaha reciever and 5.1 sound system. I dont think the problem is here, because couple of weeks ago it all worked like a charm. Come to think of it, the sound problem may have started around the time I coppied the music in mp3 in the Caesar 3/mp3 folder [https://github.com/bvschaik/julius-support/releases/tag/music](url), but I didnt think this is causing the problem, because it worked for some time and Ive already deleted it and reinstalled couple of times to no avail.
Anyways, thanks from Czech rep., both Julius and Augustus are working fine on my MacAir at work and it has been awesome to eperience C3 again after almost 20 years 👯 !

**Comment by crudelios** [comment]
Can you please to the following:

1. Start the game
2. Wait for sound to stop
3. Open a city
4. Close game
5. Post log again

Thanks!

**Comment by Vlasta3000** [comment]
> Can you please to the following:
> 
> 1. Start the game
> 2. Wait for sound to stop
> 3. Open a city
> 4. Close game
> 5. Post log again
> 
> Thanks!

Ok, here it is
[julius-log.txt](https://github.com/bvschaik/julius/files/6057191/julius-log.txt)

**Comment by crudelios** [comment]
Having a look at the log, I believe this is either an SDL or an audio driver issue, because according to the log there is no issue loading the musics themselves.

If your computer has an headphone out, can you please try running the game with headphones to see if the issue persists? We'll probably need to dig deeper for this one...

**Comment by Vlasta3000** [comment]
Hi all! Sorry for the delay. I just tried headphones in both front and back panels of the PC but sound manager wont detect neither of them. The headphones itself work fine, but theyre from Apple, so maybe theres some problem with that. I´ll try get some other jack phones but that wont be until day after tomorrow im afraid. Anyway thank all of you!

**Comment by crudelios** [comment]
Thanks, no problem, we will wait for your feedback!

**Comment by bvschaik** [comment]
@Vlasta3000 Do you have any updates on this issue?

**Comment by Vlasta3000** [comment]
Hi and sorry again for not being active, had some personal issues. Anyway, Ive managed to get "classic" jack headphones that Win recognises and ill be damned it works! As long as the headphones are in the music and sounds work well. As soon as I unplug them, I can hear music from speakers for about 2 seconds and then it cuts out. Confusing, isnt it?

**Comment by bvschaik** [comment]
It looks like either [SDL_mixer](https://github.com/libsdl-org/SDL_mixer) (the library we are using for audio) crashes due to something in your setup, or your audio driver fails for some reason, or a combination of both. Since sound works OK over headphones it doesn't appear to be a problem with Julius, and the fact that it used to work before, while the SDL_mixer library hasn't been updated in years, indicates that the problem might be some driver for your sound setup.
Since there's nothing we can really do about it I'm going to close this issue.
