### ISSUE TITLE
Problem with marble trade

### ISSUE THREAD

**Issue by Urides** [bvschaik/julius#603]
Hello,

I just finished the ninth mission, playing in the city of Damascus, using julius-1.6.0-linux.AppImage.
 
During the whole play, I was never able to import marble from the city of Tarsus. The figures were always 0 / 0 :

![1](https://user-images.githubusercontent.com/24555008/118128015-e2472f80-b3e9-11eb-89df-187a1a16a35b.png)

The marble never appeared in my counsellor's window :

![2](https://user-images.githubusercontent.com/24555008/118128157-0d318380-b3ea-11eb-9bcb-72b58022f4cc.png)
 
First possibility : it's not possible to import marble from this city, so the item shouldn't appear in the list of what you can import from Tarsus.

Second possibility : it is possible to import marble from Tarsus, but there is problem with the max items you can import.

Thanks!

**Comment by bvschaik** [comment]
Your first possibility is the correct one: it's an oversight by the original Caesar 3 developers, who assigned marble to Tarsus but didn't specify an amount. This is also the case in original Caesar 3, see for example [this topic from 2000](https://caesar3.heavengames.com/cgi-bin/caeforumscgi/display.cgi?action=ct&f=2,2717,,all).

Since this is also an issue in Caesar 3 I'm closing this.
