### ISSUE TITLE
can not change governor name

### ISSUE THREAD

**Issue by biji** [bvschaik/julius#626]
Can not change governor name on start, but backspace and cursor keys work

Thanks

**Comment by bvschaik** [comment]
Could you please provide more information?

- What operating system do you use? From your issue on the Flathub package I guess Linux, but which distro and version?
- Which version of Julius are you running?
- Which language of Caesar 3 do you use?
- What type of keyboard do you have? And which layout/language do you use?
- What exactly happens when you type a letter? Nothing or does it result in a `?` in the input?

**Comment by biji** [comment]
Yes.. I'm using fedora 35
Julius version 1.6.0 , c3 english language
nothing happens when typing a letter, but backspace delete character

**Comment by crudelios** [comment]
That's new.

What about on the "load game" window? Does typing work?

Also, what if you click on the `The new governor` input field first and then try typing?

Thanks for your feedback!

**Comment by bvschaik** [comment]
Biji is using the Flatpak image, for which we don't provide unstable builds. I just managed to reproduce it on a Fedora 35 virtual machine, still investigating why this happens.

**Comment by bvschaik** [comment]
I found the cause, it's a combination of several things:

1. SDL 2.0.16 changed the way text input is handled on the Wayland driver: `SDL_HasScreenKeyboardSupport()` now returns `true`, causing SDL to NOT start text input on init, and therefore no text input events are received. That means that anything typed will not show up. Hotkeys (including backspace, arrow keys, etc) do work because they don't use the text input but the actual key presses.
2. The Flatpak build is using the Wayland driver by default (with fallback to X11).
3. A few weeks ago, the underlying system by the Julius flatpak image was upgraded from Freedesktop 19.08 to 21.08, this caused the SDL version to be bumped up to 2.0.16.

Non-flatpak builds which use the Wayland driver will have the same problem. Luckily SDL still prefers X11 over Wayland so I'm guessing not many users are affected.

As short-term solution, you can downgrade Julius to the version before the Freedesktop upgrade using the following command:
`flatpak update --commit=af0f78d1d5cba4ce2867e845bec455c44682b1ce05bf8125c32e29df7c84eafd com.github.bvschaik.julius`

This will give a warning that Freedesktop 19.08 is no longer supported.

We were already preparing a new 1.7 release for Julius, in which I will fix this issue properly. Hopefully we can get it released the coming week (when #627 is resolved).

**Comment by crudelios** [comment]
Great, another bug fixed 🙂
