### ISSUE TITLE
(C3 Map Editor) Meat icon replaced by Fish icon on Empire Map

### ISSUE THREAD

**Issue by Ouaz** [bvschaik/julius#661]
Hello, I don't know if this has been already reported:

In the C3 Map Editor, Meat icon is not displayed when checking goods available in any city (our city or any trading city) on the Empire Map, and is replaced by Fish icon.

For example, Mediolanum in Empire State 4:

- In C3 vanilla:

_Meat icon there._
![mediolanum4_vanilla](https://user-images.githubusercontent.com/11946570/201502006-62d90ebb-5cab-4dad-ad8a-5bbbaa683133.png)

- In Julius 1.7.0.46 (and Augustus too):

_Fish icon displayed instead of meat._
![mediolanum4](https://user-images.githubusercontent.com/11946570/201502024-6f200158-167e-4246-a2bd-f39097bfe779.png)

Thank you for reading.

**Comment by bvschaik** [comment]
Good catch! I had a look at the code and compared with how the original editor behaves.

Background: under the hood in the game, meat and fish are the same resource type; only the presence/absence of wharves determines whether the fish or meat icon is shown.

For the game: all icons, including those on the empire map are subject to the same logic:
```
if (scenario allows fishing wharves) {
    icon = fish
} else {
    icon = meat
}
```

For the editor, Julius (and Augustus) use the same logic as the game: if you disable fishing wharves in the allowed buildings setting, the icon on the empire map changes back to meat.
In the original editor, the meat icon is shown everywhere. It could be that this is intentional, it could also very well be that they simply forgot about it and it's a "bug" in the original editor.

Now, there are a few places where this meat/fish icon is used in the editor:
- Price changes
- Requests
- Demand changes
- Empire map (both for your own city and for trade)

For the first three, I think it's best if we keep the fish icon if fishing is enabled. What do you think?

For the empire map: I see a few options:
- Keep the behaviour as-is for Julius/Augustus (which is confusing for your own city's resources)
- Change to meat only for your own city but keep trade routes on meat or fish depending on settings
- Change to meat for both own city and trade cities

What do you think would be more logical?

**Comment by Ouaz** [comment]
Hello! Thanks for the detailed answer.

> In the original editor, the meat icon is shown everywhere. It could be that this is intentional, it could also very well be that they simply forgot about it and it's a "bug" in the original editor.

Oh yes, my mistake, it's likely a "discrepancy" bug in C3 vanilla, due to the fact that either Meat **or** Fish icon can be displayed in the editor (not both at the same time, because of how it works in the campaign). I understand now why devs used the "_Fishing OK / No Fishing_" description rather than using the Fish icon as an available good in your own city.^^

Whereas it works when your own city can produce Meat, this causes a "discrepancy" with trading cities buying Meat (`Miletus Empire state 27`), when your own city is not supposed to be able to produce/buy Meat (as fishing is allowed). Or trading cities selling Meat although Fishing is allowed in your own city (`Mediolanum III Empire state 29`).

Though, as you said, in Julius/Augustus, Fish or Meat icon is displayed everywhere on the empire map depending if Wharves are enabled or not in the editor (something you added then?).

So the discrepancy can not be totally fixed, but at least lessened with the third option you suggested:

> For the empire map: I see a few options:
> Change to meat only for your own city but keep trade routes on meat or fish depending on settings

- Always display ![meat](https://user-images.githubusercontent.com/11946570/201541856-1593695e-8f02-403e-a411-46dbac77db8b.png) by default for available goods in your own cities (there's nine Empire States with No fishing and Meat available in your own city). Then Wharves must be disabled by the player, so Trade Routes will have the Meat icon displayed too (no trade city can sell/buy Fish anyway)

- If Fishing is OK in the Empire State, due to the original C3 design, there's no ![fish](https://user-images.githubusercontent.com/11946570/201541972-b4720437-af0f-45c6-8497-41f7dcc1c610.png) displayed as available goods in your own city (and producing meat is not possible). So Wharves must be enabled by the player, and Trade Routes will have the Fish icon displayed (no trade city can sell/buy Meat).

This way, if an Empire State with _No Fishing_ is selected, the Meat icon will be at least displayed for your own city. The player must then disable Wharves to display also the Meat icon on Trade Routes.

I think this is the best solution to make things a bit more consistent (if I did not make a mistake). ^^

**Comment by bvschaik** [comment]
> Fish or Meat icon is displayed everywhere on the empire map (and in the editor panels) depending if Wharves are enabled or not (something you fixed from Vanilla then?).

Apparently 😉 I simply copied the logic from the game and never noticed that the editor worked differently.

> Only difference is that Augustus lists Fish or Meat depending on the setting

For Julius that wasn't done because the original game doesn't have a string for "Fish", only "Meat".

I also think that the option to fix it only for your own city is the most logical choice: I'll make that change.
