### ISSUE TITLE
The garden tiles are different from the original design.

### ISSUE THREAD

**Issue by opled2** [bvschaik/julius#693]
Nice to meet you. Thanks to your development, I am enjoying the game.

It seems that the garden tiles are applied differently in the Julius mode compared to the original version.

In the original version, even if there is a garden as shown below, the lion would still reach the Colosseum
![original_ver](https://github.com/bvschaik/julius/assets/135524071/8d2394d2-28e4-4be1-b94e-58e1ede275a6)

However, in the Julius mode, it seems that the garden is not recognized as a road, as both the Colosseum and the chariot are affected
![julius_ver](https://github.com/bvschaik/julius/assets/135524071/5da93ba7-1842-4ffc-9a34-ab36a48e928b)

Can you please check if this is correct

**Comment by crudelios** [comment]
Hi,

This is strange, coding wise there doesn't seem to be anything wrong.

Can you provide the save file, please? Thanks!

**Comment by bvschaik** [comment]
I think I know what's up: the Chinese version of the game got a botched 1.1 patch that didn't include all the fixes.

This garden issue is actually a bug that was fixed in the official 1.1 patch, but somehow was not included in the Chinese version. See also: https://github.com/bvschaik/julius/issues/197

**Comment by opled2** [comment]
this is my save file,

thank you


-----Original Message-----

**Comment by bvschaik** [comment]
> Are you saying that it's true that garden tiles are not recognized as roads (due to a patch)?
> 
> I understood that regular citizens cannot pass through garden tiles, but purpose-driven citizens (with clear starting and ending points) can.

Citizens with a destination will still go through gardens, but _only_ if the source and destination buildings are _also_ connected via a road. If the path through the gardens is shorter than the normal road, they will take the gardens. This was changed in the 1.1 patch for all versions apart from Chinese, for some reason.

Since the Chinese version is a bootlegged (non-official) one, we stick to the behaviour of the original (with 1.1 patch) for Julius.

**Comment by opled2** [comment]
I understand what you’re saying. However, based on the picture you provided, it appears that when you run the c3.exe from your Caesar 3 folder, the citizens can pass through the garden tiles and reach their destination. But in the Julius version, they don’t start their journey towards the destination.

You mentioned that the Windows version has the 1.1 patch applied, but you’re experiencing this issue specifically in the Julius mode. That’s what you’re inquiring about.

thank you,



네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Bianca van ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2023. 6. 5 오후 2:41:16
제목: Re: [bvschaik/julius] The garden tiles are different from the original design. (Issue #693)


Are you saying that it's true that garden tiles are not recognized as roads (due to a patch)?
I understood that regular citizens cannot pass through garden tiles, but purpose-driven citizens (with clear starting and ending points) can.

Citizens with a destination will still go through gardens, but only if the source and destination buildings are also connected via a road. If the path through the gardens is shorter than the normal road, they will take the gardens. This was changed in the 1.1 patch for all versions apart from Chinese, for some reason.
Since the Chinese version is a bootlegged (non-official) one, we stick to the behaviour of the original (with 1.1 patch) for Julius.

**Comment by opled2** [comment]
Please disregard the previous message. I understand now. Thank you for your response


-----Original Message-----
