### ISSUE TITLE
Enhancement for sidebar unemployment

### ISSUE THREAD

**Issue by feiyunw** [bvschaik/julius#719]
See PR #718 
This is a UI enhancement suggestion.
It is very timing critical to build structures.
A safe way to do so is to build the structure when there are enough jobless workers for it.
However, the unemployment amount, shown in the sidebar, does not fit this need very well.
The labor seekers need some time covering his service to the houses; thus, the unemployment amount is not a good indicator for consecutively building new structures.
To solve this problem, I present this modification: to show the unemployment rate title in different color, indicating whether all buildings that should have workers allocated do have them.

**Comment by bvschaik** [comment]
Let's be honest here: this is a very speed-build specific request, not of interest to normal players. In fact, we would have a hard time explaining to regular players why the title is sometimes white and sometimes green. And when it's green, it looks very much out of place since none of the other stats have a non-white color.

**Comment by bvschaik** [comment]
Closing as won't fix.
