### ISSUE TITLE
Defining useful contributions, creating CONTRIBUTING.md.

### ISSUE THREAD

**Issue by crudelios** [bvschaik/julius#73]
Now that Julius is picking up some steam, the contributions keep increasing and not all of them are deemed useful or important.

This is because Julius has a somewhat contradictory goal: on one hand, to mimic Caesar 3 as much as possible; on the other hand, to improve its usability to modern-day standards.

This ambiguity makes it hard to understand which changes may be acceptable, and which ones will change the core gameplay in such a way that it goes beyond the scope of this project.

As an example, I have three branches that I decided not to submit a pull request, because I'm not sure they would be acceptable:

- One that updates the acqueducts' layouts when they are cleared at an intersection;
- One that prevents gatehouses from adding roads on map rotate; and
- One that displays in the empire map whether a new trade route will be land or sea-based.

In order for everyone to better understand what would be welcoming changes, I think it's a good idea to define some general guidelines which could go to `CONTRIBUTING.md`.

Besides that, things like coding style and naming conventions should go there as well.

Hopefully that could help everyone provide changes that are acceptable for the project.

Here's one from my experience:
- Avoid using SDL functions that require versions higher than 2.0.0. If you absolutely need to do so, make sure those changes are optional and leave an alternative which only requires SDL 2.0.0.

**Comment by jdmillard** [comment]
A CONTRIBUTING.md is nice, but consider the following paradigm: an "enhanced" fork that adopts the non-vanilla fixes and features that are good. This could be a dev branch on a fork that _stays rebased off the upstream master_ (this could be crudelios' fork since he is very active and has several awesome features already). The frontpage readme would simply list the improvements.

The utility of this suggestion is that authors of "unuseful" PRs can pointed in the direction of the non-vanilla fork - thus keeping them in the community and keep the excitement alive.

Clearly there will be disagreements about what would go in the non-vanilla fork:branch, but that's why someone would own it like crudelios with executive.

**Comment by crudelios** [comment]
I agree that a base julius and enhanced julius could be a good way to add new features and keep the spirit of the original.

It doesn't need to be my fork, it could be a branch here or a new repo from @bvschaik.

A more cluttered alternative would be to add everything to base julius, but allow the user to decide which enhancements to enable.

**Comment by Hirosimych** [comment]
> A CONTRIBUTING.md is nice, but consider the following paradigm: an "enhanced" fork that adopts the non-vanilla fixes and features that are good.

There must be at least 3 main forks then:
- "Vanilla" - in accordance to author, a mirror of C3 with all bugs;
- "Improved Vanilla" - same C3, but without bugs, no functional enhancements;
- "Enhanced" - a bug-free version of C3 with implementation of all mechanics that was included by the Impression Games through series like storage yard/market/roadblock management, combat experience for the forts, improved walker/trade ship/restocking market lady AI, more info from the Advisors (how many free housing in city, option to set import rate, etc), ability to switch on/off individual idustry, and others.

**Comment by dalerank** [comment]
I think it need to implement throw plugin system, and player can on/off options which need

**Comment by devnoname120** [comment]
Forks are good and all until upstream repo gets refactored. Then it's an **absolute nightmare** to maintain.

Also, I'm not sure a "Vanilla" version is useful, who wants to play C3 with bugs?
Finally, having several forks risks confusing users.

If we look at the most successful reimplementations (OpenRCT2, OpenTTD) they both only have one release branch, which fixes bugs and adds various gameplay improvements. For things that change the gameplay drastically (e.g. AI changes), they have options in the menu.

**Comment by Hirosimych** [comment]
> Also, I'm not sure a "Vanilla" version is useful, who wants to play C3 with bugs?

Well, thats the autor's idea, it was supposed to be a complete mirror of the original game.

**Comment by crudelios** [comment]
Exactly.

I think keeping julius only as an open-source clone of C3 will eventually reduce its usefulness. It can be kept for historic reasons, maybe as a frozen 1.x version that will only get occasional bugfixes when new differences between julius and C3 are found.

Then there could be a 2.x version that has the new gameplay stuff/major code refactoring/etc.

**Comment by shirakaba** [comment]
> Forks are good and all until upstream repo gets refactored. Then it's an **absolute nightmare** to maintain.

I agree here, though mainly from witnessing monster codebases like React Native.

Instead of forking, you could also consider refactoring Julius as necessary (although maybe it already meets most requirements) to allow it to be consumed as an 'engine' for these more glamorous projects that aim to extend/enhance the original. This engine would have to be highly customisable to accommodate all foreseeable purposes.

This would also raise the discussion of whether Julius itself should later become a consumer of this hypothetical engine (in which case it could be thought of as the 'Julius core' or perhaps even 'citybuilders core' if it were able to be generalised enough).

The advantage of extracting a core engine for Julius to consume would be that we could run multiple repos:

1. Julius itself, aiming to accurately reproduce C3, even its bugs. Some non-intrusive quality-of-usage improvements such as screen resolution customisation may be permitted here, but certainly no new game mechanics.
2. Another project (say, "Brutus"), that accurately reproduces C3, but fixes bugs and adds minor new quality-of-gameplay improvements such as roadblocks.
3. Yet another project that adds radically new features, possibly inspired by the other Impressions games.

**Comment by crudelios** [comment]
Since there now is a CONTRIBUTING.md, this can be closed.
